Classes/Issues/Comments/Details/IssueCommentDetailCell.swift, Classes/Issues/Comments/Reactions/IssueCommentReactionCell.swift, Classes/Settings/SettingsUserCell.swift, Classes/Settings/SettingsViewController.swift, Classes/Systems/RootNavigationManager.swift, Classes/Views/ButtonCell.swift, Classes/Views/UIButton+Label.swift, Resources/Info.plist
What these changes do:
- Make the "more options" button in an issue / PR be called "More options" instead of "bullet"
- Make the "add reaction" button in a comment be called "Add reaction" instead of "plus"
- Add a button trait to both `SettingsUserCell` and `ButtonCell` to indicate these are buttons
- Make the user cell in settings make clear this is an account, and tell us when it is selected (or not)
- Make the SettingsVC dismissible with a two-finger Z-swipe in VoiceOver mode.
- Make the "settings" button be called "Settings" instead of "bullets hollow"
- Remove the button trait from buttons used as labels (eg. the "merged" / "open" / "closed" images)
=> Add clearer accessibility labels and traits

Classes/Systems/GithubAPIDateFormatter.swift, Resources/Info.plist
Fixes #64
I also think this may fix #22
So originally I was just going to add the locale and timeZone properties as per Apple's documentation [here](https://developer.apple.com/documentation/foundation/dateformatter#2528261). But then I realised we only support iOS 10+, and that gives us access to the new [`ISO8601DateFormatter`](https://developer.apple.com/documentation/foundation/iso8601dateformatter)
I gave the app a cursory glance in both 12hr and 24hr modes and it does appear to be working?
The alternative (if we wanted iOS 9 support, or if someone finds further issues with this) is, for reference:
``` swift
dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZ"
dateFormatter.locale = Locale(identifier: "en_US_POSIX")
dateFormatter.timeZone = TimeZone(secondsFromGMT: 0) …
```
=> Update to use Apple's ISO8601 Date Formatter

Classes/Notifications/NotificationsViewController.swift, Classes/View Controllers/UIViewController+Alerts.swift, Classes/Views/Strings.swift
I found the "Mark All" alert a bit strange.. this pull requests changes that to "OK" instead
From https://developer.apple.com/ios/human-interface-guidelines/ui-views/alerts/
> Give alert buttons succinct, logical titles. The best button titles consist of one or two words that describe the result of selecting the button. As with all button titles, use title-style capitalization and no ending punctuation. To the extent possible, use verbs and verb phrases that relate directly to the alert title and message—for example, View All, Reply, or Ignore. Use OK for simple acceptance. 
Also this changes "Ok" to "OK" in other places
Thx for the app!
=> [minor] Update alert text

Classes/Views/AttributedStringView.swift
Most notably caused IssuesViewController to be retained after
dismissing.
=> Fixed retain cycle related to AttributedStringView

Classes/Notifications/NotificationCell.swift
=> Added notification title constraint, close #162

TextViews.playground/Contents.swift
This fixes the playground errors and keeps the maximumNumberOfLines
property type consistent with maximumNumberOfLines on NSTextContainer.
=> Changed maximumNumberOfLines to Int from UInt

Classes/Issues/Comments/Markdown/CommentModelsFromMarkdown.swift, Classes/Issues/Comments/Markdown/MMElement+Table.swift, Classes/Issues/Comments/Tables/IssueCommentTableModel.swift, Podfile
Updated the Markdown parsing so it calls `HTMLString`'s `removingHTMLEntities`-method so the html entities get converted to the real deal like a Emoji
Fixed the issue that the height of a table row was hard-coded to `30` now it's being calculated and the biggest tone is used for all other rows
=> Added the pod `HTMLString`, fixes #307

Classes/Search/SearchViewController.swift
As system restricts Cancel button on iPad, added an option to remove search results and show recent searches when search bar text field is cleared.
=> Removes search results when search bar textfield cleared/emptied, fixes #305

Classes/Issues/Comments/Html/IssueCommentHtmlCell.swift, Classes/Issues/Comments/Html/IssueCommentHtmlModel.swift, Classes/Issues/Comments/Markdown/CommentModelsFromMarkdown.swift, Resources/Info.plist
Relates to #314 
So this does fix the issue in the GitHawk README, but we're still going to have issues with links going to relative destinations such as to a guide MD file or similar.
Thinking we need to check the file extension, see what the type is?
@rnystrom Advice?
=> Allow relative images to display in README files

Freetime.xcodeproj/project.pbxproj
Re: #114 
_This fix dropped my average re-build (no code changes) time from 60-90 seconds to 7-10 seconds._
It appears to me that the largest contributor to compile times is `API.swift` and its re-generation in the "Generate Apollo GraphQL API" build phase.
The build script currently overwrites `API.swift` on every build, resulting in a new last-modified timestamp. As such, the swift compiler won't use its cached build of the file.  (You'll have to excuse me, I don't know much about the compiler, so I may be butchering terminology.)
In my estimation, this causes XCode to not only recompile `API.swift`, but also _all files that reference its contents_.
Modify the "Generate Apollo GraphQL API" build phase to only overwrite `API.swift` if the output of `check-and-run-apollo-codegen.sh` …
=> Improve compile times (Issue #114)

Classes/Issues/GithubClient+Issues.swift, Classes/Issues/IssueResult.swift, Classes/Issues/IssuesViewController.swift, gql/API.swift, gql/IssueOrPullRequest.graphql
Closes #412 
- Get `hasIssuesEnabled` on repo level when querying for `IssueOrPullRequest` (In case if you have a better idea without modifying graphql, do let me know.)
- Adds "View Repository" alert action on issues/PR's and opens Repository view controller
For now, it is possible to go deep into navigation like Search -> Repo -> Issues -> Open Repo -> ...
Should we avoid this behaviour and show "Open Repo" only on issues from notifications?
=> [WIP] Adds "view repository" alert action from Issues

Classes/Settings/SettingsViewController.swift
- Adds `NewIssueTableViewControllerDelegate`  to settings view controller
- Navigate to Issues view controller after submitting new issue from "Report a bug"
- Present new issue view controller with `formsheet` style so it can work fine on iPad
Closes #468 , #469 and #467
=> Fixes report bug navigations for iPad

Classes/Login/OauthLogin.storyboard
Fixes #480 
- Using [size classes](https://developer.apple.com/library/content/featuredarticles/ViewControllerPGforiPhoneOS/TheAdaptiveModel.html#//apple_ref/doc/uid/TP40007457-CH19-SW4), I've tweaked the layout for the `Compact Height` size class which only affects iPhones in landscape.
- iPad remains unchanged
- For the existing vertical spacing constraints:
- I've approximately halved them for landscape
- Due to layout issues with the iPhone 5/5S/5SE:
- For all size classes, I've fixed the width and height to the logo image size (174x174)
- I've then opted to reduce the size to about 80% of the original size for the `Compact Height` size class
- I've decided on this percentage as I felt it was the reduction that looked the best but I'm open to changes! See my percentage comparisons …
=> Fix landscape view overlap for Login

Classes/Issues/AddCommentClient.swift, Freetime.xcodeproj/project.pbxproj, Resources/Info.plist
This change checks for an env variable called "DISABLE_APOLLO", and if that is present then exits successfully out of any further changes.
We shouldn't be running Apollo on CI because A. If it does actually make changes, then they should be picked up by the PR not CI as they wouldn't get committed back in, and B. it doesn't work 😅 
Files changed is difficult to see, so:
```shell
if [[ ! -z "${DISABLE_APOLLO}" ]]; then
echo "Stopping Task: Remove 'DISABLE_APOLLO' env variable to continue."
exit
fi
... Continue with old stuff
```
=> Disable Apollo when triggered via BuddyBuild

docs/_includes/header.html
Closes #437 
Added two navbar links on the blog website.
- Download app - redirects to App store
- View Resource - redirects to Githawk Repo page
This is how it looks.
On PC browser:
On Smart Phones:
=> Adds nav links for "Download App" and "View Resource" on blog

docs/_data/authors.yml, docs/_layouts/post.html, docs/_posts/2017-08-16-Rebranding.md, docs/_posts/2017-09-26-Accessibility-in-GitHawk.md, docs/_posts/2017-10-02-GitHawk-Status-September-2017.md, docs/_posts/2017-8-30-Finding-Your-App-Name.md
Closes #444 
Adds author support for the blog posts. We were using "minima" default theme, so copied `page.html` from the theme repo and edited to support the author. 
- Authors list is defined in `_data/authors.yml` 
-  If a post has `author` tag, post HTML will automatically add "Written By - Author Name"
-  Clicking Author name will redirect to web link which is defined in YML file
- Added authors for all current posts
Sample Post:
=> Adds authors support of blog

Classes/Systems/Toast.swift
Caught a bug where the Toast displays infinitely on warm start.
=> Remove toast on pan completion and avoid recenter exception

Classes/Systems/ForegroundHandler.swift
Noticed this while testing. If bg refresh happens on a warm start, opening Control Center then going back to the app will always trigger a refresh. This is b/c the bg and fg events don't totally match. Added a nullable flag to bg time too so it can be cleared.
=> Fix foreground/background notification mismatch

Classes/Issues/Comments/Html/IssueCommentHtmlCell.swift, Resources/Info.plist
Now you can select and scroll the "Sent with Githawk" footer text. 
I only tried this with the Signature and "Bug report dump" not sure where else we're using the `IssueCommentHtmlCell`. 
Also Closes #608
=> 🐛 Disable selection in IssueCommentHtmlCell

Classes/Repository/RepositoryCodeBlobViewController.swift, Resources/Info.plist
If in the future we want to be able to share a URL to the code / open the code in Safari / etc., let's create separate tickets for that and add an actionsheet at that point. This also doesn't add support to share images and other files yet, but we can easily do so once we support showing those file types.
Fixes #589
=> Adds sharing to code browsing

Classes/Search/GithubClient+Search.swift, Classes/Search/SearchViewController.swift
Tested this through a throttled Charles Proxy to ensure network requests are indeed being cancelled. 
Closes #549
=> Cancelled networking when the search cancel button is pressed

Classes/Repository/RepositoryIssuesViewController.swift, Classes/Search/SearchViewController.swift, Classes/Systems/ShortcutHandler.swift, Classes/View Controllers/RootViewControllers.swift
Removed the `ShortcutHandler.Constants` as it only had one constant anyway and it couldn't resolve `Constants.Strings.search`.
=> Move some hardcoded "Search"es to Constants

Classes/Search/SearchViewController.swift, Classes/Systems/Debouncer.swift
Closes #638
Classic race condition.
Apollo `FetchQueryOperation` is a class. 
Auto-search while typing is queuing up tasks to be fired after so many milliseconds. If the user hits enter to explicitly trigger a search during that time, we immediately start executing the search. In the mean-time, the debounced signal from the type-while-search fires, notices we're in a loading state and ends up cancelling the explicitly placed search. _because_ apollo queries are classes, and it's making the same network call, it ends up cancelling its own operation.
=> Cancelled debounce action if explicit search

Classes/Issues/IssuesViewController.swift, gql/API.swift
Whenever on a PR/Issue, when you lock it, the lock badge appears, if afterwards you close the issue, the open badge changes to close and we lose the locked badge. 
This happens because every time there's a lock or status changed event, the local changes are reset to the fetched state, which is not ideal, the local changes should be cumulative.
Steps to reproduce:
1. Lock a PR
2. Close a PR (the lock badge will disappear)
3. Refresh PR (both the close and the lock badge appear)
This solves it.
=> Fix: persist local changes

Classes/Search/SearchViewController.swift
Hi!
This PR adds keyboard handling so users will be able to scroll to the bottom of the list when keyboard is on the screen. Like here:
=> Added insets handling for SearchViewController

Classes/Issues/IssuesViewController.swift, Classes/Systems/Toast+GitHawk.swift, Classes/Utility/AlertAction.swift, Classes/Utility/HapticFeedback.swift, Freetime.xcodeproj/project.pbxproj
=> Add haptic for lock/unlock, close/reopen, bookmarking

Classes/Models/RepositoryLabel.swift, Classes/Repository/RepositoryIssueSummaryModel.swift
=> Added labels equatable check to ListDiffable isEqual method

Classes/Repository/RepositoryIssueSummaryModel.swift
=> Faster label summary equality for diffing

Classes/Bookmark/BookmarksViewController.swift, Classes/Search/SearchRecentSectionController.swift, Classes/Search/SearchRecentViewModel.swift, Classes/Search/SearchRepoResultCell.swift, Classes/Utility/DeleteSwipeAction.swift, Classes/Utility/RepositoryAttributedString.swift, Classes/Views/SelectableCell.swift, Classes/Views/UICollectionViewCell+SafeAreaContentView.swift, Classes/Views/UITableViewCell+SafeAreaContentView.swift, Freetime.xcodeproj/project.pbxproj, Local Pods/SwipeCellKit/Source/Extensions.swift
- Pulled workaround for iOS 11 & UITableViewCells from SwipeCellKit (https://github.com/SwipeCellKit/SwipeCellKit/issues/48)  (ref #679 ?)
- Made destructive swipe behavior generic
- Changed destructive swipe animation
- Matched search and bookmark cell heights
- Rolled in changes from #717 and #698 
Closes #709 #710 #705 #659
=> Unified deletion swipes

Classes/Systems/ShortcutHandler.swift
Fixes https://github.com/rnystrom/GitHawk/issues/754
- Updates the Bookmark quick action title to the plural `"Bookmarks"` vs `"Bookmark"`
=> Update Bookmark quick action title

Classes/Image Upload/ImageUploadTableViewController.swift, Classes/Issues/Assignees/IssueAssigneeAvatarCell.swift, Classes/Issues/Assignees/IssueAssigneeUserCell.swift, Classes/Issues/Commit/IssueCommitCell.swift
Can't test it on the simulator because you can't enable inverted colors there as far as I can tell. Super lame.
Ref #118
=> Ignore invert colors for profile images + image uploads

Classes/New Issue/NewIssueTableViewController.swift
When pressing cancel on the new issue vc the keyboard sticks around a bit after the vc has dismissed.
This dismisses keyboard simultaneously.
=> Adds keyboard dismiss on new issue cancel

Classes/Models/RepositoryLabel.swift
No longer necessary after #725
=> Removed Equatable comformance from RepositoryLabel

Classes/Bookmark/BookmarksViewController.swift
Closes #728 
Bonus feature from #692 - hides the search bar under the navigation bar for iOS 11. So that for smaller devices it will give some room for contents
Update:
Tested on iOS 10, 10.2 and 11
=> Fixes bookmark search behaviours 

Classes/Issues/GithubClient+Issues.swift, Classes/Issues/IssueResult.swift, Classes/Issues/IssuesViewController.swift
- Added helpers to `IssueResult` making it easy to get new, mutated objects
- Moved optimistic state stuff into client issues extension
- Removed local state mgmt from VC
- Issue VC uses `FlatCache` system to fetch data
Fixes #597
=> Issues use FlatCache for optimistic state changes

Classes/Bookmark/BookmarkModel.swift, Classes/Bookmark/BookmarksViewController.swift, Classes/Issues/GithubClient+Issues.swift, Classes/Issues/IssueResult.swift, Classes/Issues/IssuesViewController.swift, Classes/Repository/GitHubClient+Repository.swift, Classes/Repository/RepositoryCodeBlobViewController.swift, Classes/Repository/RepositoryCodeDirectoryViewController.swift, Classes/Repository/RepositoryDetails.swift, Classes/Repository/RepositoryViewController.swift, Classes/Search/GithubClient+Search.swift, Classes/Search/SearchRepoResult.swift, Classes/Search/SearchResultSectionController.swift, Freetime.xcodeproj/project.pbxproj, FreetimeTests/Search Tests/SearchQueryTests.swift, FreetimeTests/Search Tests/SearchRecentViewModelTests.swift, gql/API.swift, gql/IssueOrPullRequest.graphql, gql/SearchRepos.graphql
Closes #824 
Stores the defaultBranch off a repository and uses that for the code view. We could fetch it once the user goes to the page, but that would then require two separate requests which I felt was a tad overkill for this.
I made the conscious choice to pass the branch through to the code view rather than assuming it as the default branch from the repository details model in order to allow future expansion and link to a certain branch (#441)
Precursor to adding functionality of changing branches on the fly, even if we did support that - this functionality should be there as per GitHub desktop.
=> Use repository default branch rather than master for file view

Classes/Repository/RepositoryIssuesViewController.swift, Classes/Repository/RepositoryViewController.swift, Podfile, Podfile.lock, Pods/Manifest.lock, Pods/Tabman/README.md, Pods/Tabman/Sources/Tabman/TabmanBar/Styles/Abstract/TabmanButtonBar.swift, Pods/Tabman/Sources/Tabman/TabmanBar/TabmanBar+Appearance.swift, Pods/Tabman/Sources/Tabman/TabmanBar/TabmanBar+Insets.swift, Pods/Tabman/Sources/Tabman/TabmanBar/TabmanBar+Layout.swift, Pods/Tabman/Sources/Tabman/TabmanViewController+Embedding.swift, Pods/Tabman/Sources/Tabman/TabmanViewController+Insetting.swift, Pods/Tabman/Sources/Tabman/TabmanViewController.swift, Pods/Target Support Files/Tabman/Info.plist, Settings.bundle/com.mono0926.LicensePlist.plist
This lib had an issue with iOS 11 + iPhone X, but recent patches look like its all taken care of. This fixes the "scroll to top" issue when going back to issue/PR in a repo.
Fixes #866
=> Update Tabman with recent bugfixes

Classes/Bookmark v2/BookmarkCell.swift
fixes #883
fixes #885 
Fixed:
- Alignment issues
- Bottom border inset
- Selection behavior
How:
- Replaced using an AttributedStringView with a UILabel, continued to
use the sizing from the NSAttributedStringSizing to calculate height
- Changed styling to match the rest of the app re: insets.
=> Fixed styling and alignment issues

Classes/Bookmark v2/BookmarkViewModel.swift, FreetimeTests/Bookmark Tests/BookmarkViewModelTests.swift
Updated the bookmark subtitle color and the issue # color to medium-gray
fixes #956
=> Bookmark subtitle color

Classes/Bookmark v2/BookmarkViewController.swift, Classes/Search/SearchViewController.swift, Classes/Views/Constants.swift
Fixes #968 
Fixes #969 
This change does not touch the [repository search](https://github.com/rnystrom/GitHawk/blob/search-placeholders/Classes/Repository/RepositoryIssuesViewController.swift#L99); should that be "Search Repository"?
Also does not change the [3D Touch shortcut](https://github.com/rnystrom/GitHawk/blob/search-placeholders/Classes/Systems/ShortcutHandler.swift#L52); should that be "Search GitHub" too?
=> More expressive search placeholders

.gitignore, Classes/Image Upload/ImgurClient.swift, Classes/Login/GithubClient+AccessToken.swift, Classes/Login/LoginSplashViewController.swift, Classes/Settings/SettingsViewController.swift, Classes/Systems/Secrets.h, Classes/Systems/Secrets.m, Freetime.xcodeproj/project.pbxproj, Resources/Freetime-Bridging-Header.h
Using #197 as a jumping point, I added a new secrets setup that has:
- Ignored, generated secrets config. Update once, never touch again
- Config files are added to Xcode project file, so CI should build
- Add secrets to buddybuild as env variables
Fixes #986
=> Environment variables and secrets refactor

Classes/Issues/Comments/IssueCommentSectionController.swift
Bug from #809. If reaction cell wasn't visible, it was returning early. Make the cell optional instead. cc @joerocca
=> Allow double-tap like when reaction not visible

Classes/Issues/Comments/Text/IssueCommentTextCell.swift, Classes/Views/AttributedStringView.swift
Fixes #1018.
This adds some simple support for accessibility in the cell. It doesn't yet check if the cell is expandable and offer the option to expand it.
=> Add initial accessibility support for text cell

Classes/Image Upload/ImageUploadTableViewController.swift, Classes/Image Upload/ImgurClient.swift
Tested on an older version of master before I realised it wasn't the latest code, can't test on latest version of master because #1061 😢 
Fairly simple logic but if we get an error from Imgur we show it straight up with no magic, if it's an error enforced by us we do the rate limit error. If it's an unexpected error we just use a generic one. Atleast we know which path it went down before it failed!
"Invalid client_id" is the current one, seems fair!
fixes #1047
=> Add better error messages for Image Upload fail states

Classes/Issues/Comments/Reactions/IssueReactionCell.swift, Classes/Issues/Comments/Text/IssueCommentTextCell.swift, Classes/Issues/IssueTextActionsView.swift, Classes/Issues/Labels/IssueLabelSummaryCell.swift, Classes/Notifications/NotificationCell.swift, Classes/Notifications/NotificationNextPageCell.swift, Classes/Repository/Empty/RepositoryEmptyResultsCell.swift, Classes/Repository/RepositoryCodeDirectoryCellExtension.swift, Classes/Repository/RepositorySummaryCell.swift, Classes/Search/SearchNoResultsCell.swift, Classes/Search/SearchRepoResultCell.swift, Classes/Utility/Accessibility.swift, Classes/Views/SelectableCell.swift, Freetime.xcodeproj/project.pbxproj
Fixes #1051.
This adds an `AccessibilityHelper` that can be used to generate an accessibility label for either a `UICollectionViewCell` or `UITableViewCell`.
=> Generate accessibility labels for cells

Classes/Systems/Feed.swift
Easy to repro this currently via:
1. Search "githawk"
2. Open repo
3. Tap "Issues" tab
Observe refresh is 2x inset
=> Prevent UIRefreshControl from double inset bug

Classes/Repository/RepositoryViewController.swift
Fixes #1082.
Visual:
Bonus track, as I removed the navigationItem title (it was unused and set in `viewDidLoad()`), I added some more descriptive accessibility there:
=> Add repo+author name to action sheet, title accessibility

Classes/Views/TextActionsController.swift, Local Pods/SlackTextViewController/Source/SLKTextViewController.m
@Sherlouk was spot on!
Fixes #1095
Also changing image insertion to be at the cursor
=> Prevent SLKTextViewController cache from overwriting text

Classes/Issues/Labels/IssueLabelDotCell.swift, Classes/Views/DotListView.swift
Noticed the `reloadData` was eating a ton of perf. Also added a border so labels similar to background color are noticeable.
=> Improve scroll perf of DotListView

Classes/Labels/LabelTableCell.swift
Also makes it tappable; previously it wasn't usable at all in VoiceOver.
=> [Accessibility] Label TableCell

Local Pods/SlackTextViewController/Source/SLKTextViewController.m
Stops `SLKTextViewController` from scrolling beyond the top offset when showing the keyboard. There was an issue for this I think? I'll dig it up.
=> Don't scroll beyond the top offset

Classes/Labels/Labels.storyboard, Classes/Utility/Accessibility.swift
Fixes #1210.
This was weird - we set the checkmark `accessoryType` in the Storyboard, but even if we overwrote it in code VoiceOver would still think it was selected. 🤔
Also return early if a cell only has one accessibility label, to prevent weird unneeded `.\n`s in `accessibilityLabel`s.
(Also thanks for adding the accessibility label @rnystrom, was about to do that!)
=> Only have a label selected if it actually is

Classes/Issues/Files/IssueViewFilesCell.swift
Fixes #1239.
Opted to keep it easy ("View Files" as the label) and have the other information in the hint.
=> Add accessibility label and hint to "View Files"

Classes/Issues/Milestone/IssueMilestoneCell.swift
Fixes #1227.
The progress was actually read, but as the cell itself wasn't an accessibility element I didn't catch this. Wrapped the cell and made it more human-“readable”.
=> Add accessibility to milestone cell

Classes/Issues/IssuesViewController.swift, Classes/Models/FilePath.swift, Classes/Repository/RepositoryViewController.swift, Classes/View Controllers/UINavigationItem+TitleSubtitle.swift
Fixes #1240 
See the details for screenshots.
Bonus track: A repo already had a special label, but I've updated it to reflect the issue / pull request style (and use the `configure` func to supply the label).
Also fixed the possibility of `fileExtension` returning a folder.
<details>
**Issue / Pull request:**
**File + path:**
**Path:**
**Repo:**
</details>
=> Add + update a11x for navigation titles

package.json
When i cloned the repo and ran `npm install`, the version of apollo-codegen that npm installed on my machine was `0.17.2`. That version generated [this API.swift file](https://gist.github.com/spsjvc/6d93b02c9d09932f9ec3a99554bf7cc0) which is different than the one on `master` and breaks the build. The exact 0.17.0-alpha.13 of apollo-codegen works fine. This might be a temporary fix until the app is updated to work with the newer versions.
=> Change version of apollo-codegen to exactly match 0.17.0-alpha.13

Classes/Notifications/NotificationClient.swift, Classes/Notifications/NotificationSubscriptionsController.swift, Classes/Notifications/NotificationsViewController.swift, Classes/Utility/AlertAction.swift, Classes/View Controllers/RootViewControllers.swift, Freetime.xcodeproj/project.pbxproj
- New left/right nav bar items for inbox
- Show alert, select repo
- `NotificationsViewController` now handles unread, all, and repo (show all for repo)
- "Mark Read" for repo clears _only_ that repo's notifications
Pretty happy w/ this quick hack. Been using it all night. This will get us some immediate feedback before investing much in custom UI controls (e.g. the whole nav-bar dropdown thing).
Fixes #61
=> View notifications by repository

Classes/Notifications/NotificationsViewController.swift
Fixes #1293 
Added the Do Not Merge as there is something super strange happening I can't explain - when refreshing, the mark all is enabled for a split second. Seems to happen in [`IGListAdapter`'s `performUpdatesAnimated`](https://github.com/Instagram/IGListKit/blob/master/Source/IGListAdapter.m#L330), called by the feed's `finishLoading`.
@rnystrom, what am I overlooking?
=> [DO NOT MERGE] Switch markAll logic back to mark all

Classes/Issues/IssuesViewController.swift
`lazy var feed: Feed` results in setting the kb dismiss mode _after_ the message VC was setup.
=> Setup message control after feed is loaded

Classes/Notifications/NotificationsViewController.swift
This is more consistent since we have `View Archived` here https://github.com/rnystrom/GitHawk/blob/b9cda654a9caab61b7b690ca3bceefba240636a8/Classes/Notifications/NotificationsViewController.swift#L91
=> Rename .all title to `Archived`

Classes/Issues/IssuesViewController.swift, Classes/Issues/Managing/IssueManagingNavSectionController.swift, Classes/Issues/Managing/IssueManagingSectionController.swift, Classes/Views/HangingChadItemWidth.swift, Classes/Views/UIScrollView+ScrollToBottom.swift, Freetime.xcodeproj/project.pbxproj, FreetimeTests/HangingChadItemWidthTests.swift
Fixes #1325, #1322
- Tapping manage button now just scrolls to bottom
- Actions always displayed when you can admin
- Adjust layout math to evenly distribute options, no single action hanging
=> Manage button scrolls to bottom to reveal actions

Classes/Notifications/NotificationsViewController.swift
This is asserting when the right bar item is a spinner. Removing. cc @BasThomas
=> Remove assert firing on wrong bar item

Classes/Systems/NSAttributedStringSizing.swift, Local Pods/StyledText/StyledText/CGImage+LRUCachable.swift, Local Pods/StyledText/StyledText/CGSize+LRUCachable.swift, Local Pods/StyledText/StyledText/Hashable+Combined.swift, Local Pods/StyledText/StyledText/LRUCache.swift
Excited to see this in action. You can now open tons of issues and memory doesn't continue to grow.
Atm the `FlatCache` uses a singleton that stores models holding refs to `NSAttributedStringSizing`. These string objects only purge memory on warning which could be too late. Now we cap at 20mb (the default that the `StyledText` lib uses, migration is tbd tho).
=> Use lru cache for current bitmap caching

Classes/Issues/EditComment/EditCommentViewController.swift
=> Make edit comment keyboard use the Twitter style

Classes/Issues/IssuesViewController.swift, FreetimeTests/MMMarkdownASTTests.swift
Fixes #1408 
Also fixes a warning in the test suite.
=> Distinguish owner from repository in dropdown actionsheet

Classes/PullRequestReviews/PullRequestReviewReplyCell.swift
Old:
New:
(Feel free to ignore the underlined buttons - that's button shapes for you)
=> Adds (better) a11x to Pulll Request reply

Classes/Search/SearchRepoResultCell.swift
This resolves #1505 by setting a lower horizontal compression priority on the repo's description label. Just a small PR to break the ice here. Better to fix things than be the guy complaining all the time 😃
=> Fix star count label compression #1505

Classes/Issues/EditComment/EditCommentViewController.swift, Classes/Views/IssueTextActionsView+Markdown.swift, Classes/Views/MessageView+Styles.swift
Resolves #1481 
This adds the `@` mention symbol as a shortcut to `IssueTextActionsView`. I've also changed the `UIKeyboardType` from `.twitter` to `.default`, so we regain the return key.
The `.twitter` keyboard makes it very easy to add both `#` and `@`. 
Do we want to wait for #219 to add `#`?
=> Add mention shortcut to IssueTextActionsView

Classes/Issues/IssueTextActionsView.swift, Classes/Views/IssueTextActionsView+Markdown.swift, Classes/Views/TextActionsController.swift
Resolves #1453 
This PR does the following:
- Automatically displays the paste menu upon using the link markdown action if the `UIPasteboard` contains a `URL`
- Refactors the order of the `switch` statement to check more frequent `Operation`s first
If this is too much of a hack I can try to create an indirect enum that allows both a `.wrap` and `.execute` but why get fancy until it's necessary?
=> Display paste menu on URL wrapping

Freetime.xcodeproj/xcshareddata/xcschemes/Freetime-AppCenter.xcscheme
Fixes #1535 
Removes the pre-configured GitHub client ID and secret. This has the advantage that if the user doesn't have them set in their environment an explicit error message will be displayed.
=> Check if default value is for client ID and secret is set

Classes/Search/SearchViewController.swift
This resolves #1557 with the agreed upon solution.
We'll only save user selections as recent searches and not query terms.
=> Only save selections as recent searches

Classes/Image Upload/ImageUpload.storyboard, Classes/Image Upload/ImageUploadTableViewController.swift
Fixes #1527
* Remove the description text field
* When a title is set, use it as alt text
* When return on keyboard is tapped, close keyboard
* Increase size of image view
=> Remove image upload description

Classes/Systems/AppDelegate.swift, Classes/Systems/RootNavigationManager.swift, Classes/Systems/Route.swift, Classes/Systems/ShortcutHandler.swift, Classes/View Controllers/TabBarController.swift, Freetime.xcodeproj/project.pbxproj, Resources/Base.lproj/Main.storyboard
Hopefully fixes #708 and give us a way of handling deep linking possibilities.
- Adds `Route` enum with possible routes - extensible 
- Adds `TabBarController` with `Tab` enum
- Refactores `ShortCutHandler` to use `Route`
Now adding deep linking with `Route` is as easy as like below
```swift
init?(url: URL) {
switch url.absoluteString {
case "\(scheme)://tab/inbox": self = .tab(.inbox)
case "\(scheme)://tab/search": self = .tab(.search)
case "\(scheme)://tab/bookmars": self = .tab(.bookmarks)
case "\(scheme)://tab/settings": self = .tab(.settings)
default: return nil
}
}
```
Not sure this is the right/scalable way. Feel free to comment/suggest/close this PR.
=> Refactoring shortcut handler to use enum based Routes

Classes/Notifications/NotificationViewModel.swift
Been bugging me forever. Update the time-since-updated label based on UI values, not the actual date. This will trigger a reload of the cell.
=> update notification cells when ago string changes

Classes/Bookmark/BookmarkViewModel.swift, Classes/Notifications/Notification+NotificationViewModel.swift, Classes/Notifications/NotificationClient.swift, Classes/Notifications/NotificationSectionController.swift, Classes/Notifications/NotificationType+Icon.swift, Classes/Notifications/NotificationType.swift, Classes/Notifications/NotificationViewModel.swift, Classes/View Controllers/UIViewController+Safari.swift
Only thing I can't quite figure out is how to link to it... We get an API path that we can extract the id from, like this:
https://api.github.com/repos/facebook/Docusaurus/releases/9721470
Where `9721470` is the ID. But I'm not sure how to link it to [the actual release](https://github.com/facebook/Docusaurus/releases/tag/v1.0.7).
Any ideas?
Shot of it working:
=> Release notifications

Classes/Login/OauthLogin.storyboard
I think it's time for my first contribution. Since I started playing around with the code and storyboards, I observed the the UI in Sign in screen (especially in smaller screens like a 4s looks a bit weird). This PR adresses exactly that.
Before | After
------------ | -------------
=> Sign in Screen: Fix UI in smaller screens

Classes/Utility/UIDevice+Model.swift
This was caught by static analysis in Xcode 9.3, cool 😎
=> Remove duplicate iPad7,3 case

Classes/Bookmark/BookmarkCell.swift, Classes/Bookmark/BookmarkSectionController.swift, Classes/Bookmark/BookmarkViewController.swift, Classes/Bookmark/BookmarkViewModel.swift, Classes/Issues/GithubClient+Issues.swift, Classes/Issues/Issue+IssueType.swift, Classes/Issues/IssueType.swift, Classes/Issues/PullRequest+IssueType.swift, Classes/Issues/Renamed/IssueRenamedCell.swift, Classes/Issues/Renamed/IssueRenamedModel.swift, Classes/Issues/Renamed/IssueRenamedSectionController.swift, Classes/Issues/Renamed/IssueRenamedString.swift, Classes/Repository/RepositoryClient.swift, Classes/Repository/RepositoryIssueSummaryModel+Filterable.swift, Classes/Repository/RepositoryIssueSummaryModel.swift, Classes/Repository/RepositorySummaryCell.swift, Classes/Repository/RepositorySummarySectionController.swift, Classes/Systems/NSAttributedStringSizing.swift, Classes/Views/AttributedStringView.swift, Classes/Views/MarkdownAttributeHandling.swift, Freetime.xcodeproj/project.pbxproj, FreetimeTests/Bookmark Tests/BookmarkViewModelTests.swift, Podfile.lock, Pods/Manifest.lock, Pods/StyledText/StyledText/CGSize+Utility.swift, Pods/StyledText/StyledText/NSLayoutManager+Render.swift, Pods/StyledText/StyledText/StyledTextRenderCacheKey.swift, Pods/StyledText/StyledText/StyledTextRenderer.swift, Pods/StyledText/StyledText/StyledTextString.swift, Pods/StyledText/StyledText/StyledTextView.swift
=> Start refactoring text views with StyledText

Classes/Settings/SettingsViewController.swift, Classes/Views/Constants.swift
Fixes #1629 
- Changes the `"View Source Code"` action to open the GitHawk in GitHawk vs SafariVC
- Removed `URLs.repository` constant from `Constants` as it's no longer being used
- **Note:** This will no longer work if the repo or owner name change
- However, the same issue would happen with the url approach too.
=> Enable view source to open in GitHawk

Classes/Settings/SettingsViewController.swift
It was created as SettingsViewController2, but now it is called SettingsViewController.
=> File name in comments not matching real file name

Classes/Bookmark/BookmarkNavigationController.swift, Classes/Issues/IssuesViewController.swift, Freetime.xcodeproj/project.pbxproj, FreetimeTests/Bookmark Tests/BookmarkNavigationItemTests.swift
fixes #1700 
Sets up a disabled placeholder bookmark button in navBar during viewDidLoad, then configures the button after the Issue loads, instead of waiting until the Issue loads to put the bookmark button in the navBar. 
Feels like a bit much in terms of refactoring for such a small issue. No worries if that's the case.
=> update bookmark nav item state between viewDidLoad and Issue Load

FreetimeTests/IssueTests.swift
#120 doesn't seem to be an issue any longer
=> Brackets inside link text fixed

Freetime.xcodeproj/project.pbxproj, FreetimeTests/NetworkingURLPathTests.swift, Local Pods/GitHubAPI/GitHubAPI/V3AddPeopleRequest.swift
Changed the path component for adding reviewers. Hopefully resolves #1829.  I'm basing the change off the API docs and the unit tests.. I'm not sure how to reproduce this issue manually in the app. 
Also, the unit tests use GithubClient to send the requests as opposed to a URLSession.. the downside being that a failed test doesn't give you much info other than "not a ClientError.unauthorized i.e. 401 response". If it would be preferable to use a URLSession that gives a regular status code to test against, let me know and I'll swap them out.
=> updates add reviewers url path

FreetimeTests/NetworkingURLPathTests.swift
From #1832. These tests are doing real networking which should be faked instead.
=> Disable flaky tests

Classes/Issues/Managing/IssueManagingSectionController.swift, Classes/People/PeopleViewController.swift
Fixes #1850
This pulls out the PR author from the `IssueResult` and filters out the author from the list of potential reviewers.
I was originally going to change `IssueResult` to include an author object but saw that the author is referred to using the root comment [here](https://github.com/GitHawkApp/GitHawk/blob/master/Classes/Issues/GithubClient+Issues.swift#L94-L101)
=> Do not allow review request from PR author

README.md
URL to clone repo from in installation steps was outdated.
=> Update outdated URL in Readme

Classes/Settings/Settings.storyboard, Classes/Settings/SettingsViewController.swift
Storyboard changes are due to the new cell addition. Y pos of each cell in 2nd section were moved down as the new cell was placed on the very top.
=> [Settings]  [Issue #1927] Added Rate on App Store cell 

Classes/Issues/IssueManagingContextController.swift, Classes/View Controllers/ContrastContextMenu.swift
=> [Issue #1923] Added color to constrastContext struct

Classes/Issues/Comments/Details/IssueCommentDetailCell.swift, Local Pods/DateAgo/DateAgo/Date+AgoString.swift
=> Fixed badge alignment

Classes/Bookmark/BookmarkViewController.swift, Classes/Issues/Comments/IssueCommentSectionController.swift, Classes/Issues/Files/IssuePatchContentViewController.swift, Classes/Issues/GithubClient+Issues.swift, Classes/Issues/IssuesViewController.swift, Classes/Issues/Preview/IssuePreviewViewController.swift, Classes/Milestones/GithubClient+Milestones.swift, Classes/Notifications/NotificationModelController.swift, Classes/PullRequestReviews/GithubClient+PullRequestReviewComments.swift, Classes/Repository/RepositoryClient.swift, Classes/Repository/RepositoryOverviewViewController.swift, Classes/Systems/Autocomplete/AutocompleteCell.swift, Classes/Utility/UIContentSizeCategory+Preferred.swift, Classes/Views/Styles.swift
According to #2029
**Changes:**
- Added static property preferred to UIContentSizeCategory - now we can use this property instead of UIApplication.shared.preferredContentSizeCategory.
=> Fixed preferredContentSizeCategory called on background thread issue

Classes/Issues/Merge/MergeButton.swift
Feels like an easy UI win: 
before: 
after:
=> add gradient to mergeButton

SECURITY.md
This pull request addresses https://github.com/GitHawkApp/GitHawk/issues/2060 by adding a security FAQ document that answers questions about how GitHawk handles its privileged access to private GitHub user data. This document should be made accessible on githawk.com - it doesn't necessarily need to live in this repo.
I am not a regular contributor to GitHawk, so my answers to the questions in the FAQ are best guesses based on the very small amount of information I have about the project's internals. Someone familiar with the actual answers to these questions should make comments on this pull request correcting or improving my answers.
=> Security FAQ

Classes/View Controllers/ContrastContextMenu.swift
quick patch for the imageViews in contextMenu having variable widths (between 18 and 25 pt). 
before: 
after: 
I'm reluctant to change the imageView's frames as I think the system does a good job of laying them out as is, but I'm all ears if you all have suggestions for a better way to do this.
=> lines up contextMenu labels

Classes/Issues/Merge/MergeButton.swift
reverted back to the original ternary operation to set the background and such, fixes #2075.
=> mergeButton background bug fix

Classes/Issues/Comments/IssueCommentBaseCell.swift, Classes/Issues/Comments/IssueCommentSectionController.swift, Classes/Issues/Comments/Reactions/Defaults+Reaction.swift, Classes/Issues/Comments/Reactions/ReactionContent+ReactionType.swift, Classes/Settings/DefaultReactionDetailController.swift, Classes/Settings/Settings.storyboard, Classes/Settings/SettingsViewController.swift, Classes/Views/StyledTableCell.swift
Allowing users to choose the reaction that occurs when double tapping on a comment
=> Choose double tap

Classes/Issues/Comments/IssueCommentBaseCell.swift, Classes/Issues/Comments/IssueCommentSectionController.swift, Classes/Issues/Comments/Reactions/Defaults+Reaction.swift, Classes/Issues/Comments/Reactions/ReactionContent+ReactionType.swift, Classes/Settings/DefaultReactionDetailController.swift, Classes/Settings/Settings.storyboard, Classes/Settings/SettingsViewController.swift, Classes/Views/StyledTableCell.swift, Freetime.xcodeproj/project.pbxproj
From #2022 cc @Huddie 
There were enough changes that it would've taken a while to update. Some things that I want to call out:
- Explicit "disabled" value vs hacking `"Disabled"` into the unknown value
- Localization for disabled
- Code formatting! 4-space tabs, `{` on sameline (TODO SwiftLint....)
- Fixed up some naming
- Files weren't added to .xcodeproj, build was failing
=> Clean up reactions settings

Classes/Issues/IssueTextActionsView.swift, Classes/Issues/IssuesViewController.swift
=> Disable the send button when text is empty

Setup.md
Only edit here is I copied/pasted the whole 4th item (Setting up OAuth for login) and put it at the 3rd spot. 
Ordered this way, you can get the project running on your simulator in steps 1-3. The 4th item shows you how to run the project on your phone. For newcomers, it's more encouraging to get the project running on the sim as soon as possible + lowers the barrier to entry.
=> reorder setup page

Classes/Issues/Comments/Tables/IssueCommentTableCell.swift, Classes/Issues/Comments/Tables/IssueCommentTableModel.swift, Classes/Issues/IssueCommentModelHandling.swift
Noticed this investigating #2108
=> Fix bug where table cells wrap when cell collapsed

Classes/Bookmark/BookmarkSectionController.swift
Fixes #2099 
**Note:**
I think we shouldn't use the same cell for Search and Bookmarks because of they different in behavior
=> Use same cell size for Search and Bookmarks

Classes/Issues/IssueTextActionsView.swift, Classes/Issues/IssuesViewController.swift
Addresses #2154 
Not sure why "Something went wrong" but it worked. My additions shouldn’t change anything in networking.
=> Adds loading on send

Classes/Notifications/NoNewNotificationsCell.swift, Classes/Notifications/NoNewNotificationsSectionController.swift, Classes/Notifications/NotificationsViewController.swift, Classes/Views/Constants.swift, Classes/Views/Styles.swift
Updated from #2085 
If you want to see how it looks on your sim, return an empty array [here](https://github.com/GitHawkApp/GitHawk/blob/966cb1a4d1238bc2e92a42afbaacd3b6ba497d6e/Classes/Notifications/NotificationsViewController.swift#L266)
Final:
=> adds review GitHubAccess button to notifications view controller

Setup.md
This is a documentation-only change to the code signing instructions.
=> Grammatical change to code signing instructions

README.md
=> Add TestFlight link to README

Classes/View Controllers/TabBarControllerDelegate.swift
this bug is caused by the time interval between two taps which is too small.
=> fix double tap tab invalid

Classes/Section Controllers/LoadMore/LoadMoreCell.swift
Turns out Styles.Colors.Blue.light is pretty similar (if not exactly the same color as the table view background) making it unreadable 😁.
The issue was clear in the issues list (Looks like an empty cell on the bottom but it is clickable)
=> Fixed color issue

Classes/Labels/LabelsViewController.swift, Classes/Milestones/MilestonesViewController.swift, Classes/People/PeopleViewController.swift, Classes/Systems/Feed.swift, Classes/Views/EmptyLoadingView.swift
The loading spinner's default color was grey and that comes off as hard to see against Milestone's background: 
Updated to white it is more visible:
=> allows setting Milestone's loading indicator's color 

Classes/Notifications/NotificationModelController.swift, Classes/Systems/AppDelegate.swift, Classes/Systems/BadgeNotifications.swift, Classes/Systems/LocalNotificationsCache.swift, Classes/Systems/RootNavigationManager.swift, Freetime.xcodeproj/project.pbxproj, FreetimeTests/LocalNotificationCacheTests.swift
- Add some tests
- Fix settings iOS 12 issue
- Don't allow duplicate inbox requests from bg fetch
Fixes #2181
=> Fortify local notifications code

Classes/Notifications/NotificationsViewController.swift
I think the filter icon @rnystrom showed from noun project is good so this is unnecessary if we go with that one. But until then this fixes a mistake where the image name was changed in one of my merges.
=> 3 dot icon

Classes/Issues/Merge/IssueMergeSectionController.swift, Classes/Views/CardCollectionViewCell.swift
The issue before was caused by the fact that we never had less than 2 cells for the mergeSectionController to render. (Summary + Merge Button) 
Our border enum had 3 options, head, tail, neck which works well for 2+ cells (Head + Tail) but with only 1 we had issues (Just summary cell since the button is not added).
I added .full to the enum and checked if the head = the tail.
=> Fixed cell border on merge button

Classes/Systems/InboxZeroLoader.swift
Fixes #2164 
Holidays are all copy/pasted US holidays in [the repo](https://github.com/GitHawkApp/Holidays), but its open for anyone who wants to PR localized holidays!
=> Localize Inbox Zero and allow for per-year holidays

Classes/Repository/RepositoryBranches/RepositoryBranchesViewController.swift, Classes/Repository/RepositoryViewController.swift, Freetime.xcodeproj/project.pbxproj, FreetimeTests/SwitchBranches.swift
#2223 
- added func to order branches + unit tests
- replaced 'var branch: String' w/ 'private(set) var selectedBranch: String'
& added a defaultBranch variable
- changed fetch(page:) to update(animated:) in didSelect(value:) - an oversight from original pr
=> Order repo branches after fetch

Classes/Issues/Comments/Markdown/CMarkParsing.swift, Classes/Issues/Comments/Markdown/StyledTextBuilder+NewBase.swift, Classes/Repository/RepositoryOverviewViewController.swift, FreetimeTests/IssueTests.swift
=> Fix readme duplicate identifier asserts

Classes/Issues/Comments/IssueCommentSectionController.swift, Classes/Repository/RepositoryCodeBlobViewController.swift, Classes/Repository/RepositoryCodeDirectoryViewController.swift, Classes/Repository/RepositoryViewController.swift, Classes/Utility/AlertAction.swift
Adds in the feature for more share options when browsing a repository (#2161)
- Adds the `...` when viewing a directory
- Changes the share button to `...` when viewing a file
- Adds "Copy Path", "Copy Name", "Share URL", and "Share Content" options
- each option will open the share sheet giving you the option to share with a different app or just copy it to the clipboard.
For a file `Classes/Issues/Files/IssueFileCell.swift`
- Copy path: `Classes/Issues/Files/IssueFileCell.swift`
- Copy name: `IssueFileCell.swift`
- Share URL: `https://github.com/GitHawkApp/GitHawk/blob/master/Classes/Issues/Files/IssueFileCell.swift`
For a directory `Classes/Issues/Files`
- Copy path: `Classes/Issues/Files`
- Copy Name: `Files`
- Share URL: `https://github.com/GitHawkApp/GitHawk/tree/master/Classes/Issue …
=> Adds more share actions when browsing a repository (#2161)

Classes/Settings/Settings.storyboard
Fixes #2190 
Looks like "constraint to margin" is messing up on new iPhones. 
After the fix on iPhone XR
=> Fixes settings write review indent

Classes/Bookmark/BookmarkNavigationController.swift, Classes/Issues/IssuesViewController.swift, Classes/Utility/AlertAction.swift
Moves the bookmark icon for both the IssueVC and RepoVC and address some code review comments here (https://github.com/GitHawkApp/GitHawk/pull/2237#discussion_r223454940) 
**RepoVC**
**IssueVC**
=> move the bookmark icon for the RepoVC and address a CR comment

Classes/Settings/Settings.storyboard
- Changes segue kind from show to showDetail
- Adds a navigation controller for "Double tap Reaction" view controller so it will work on both iPhone, iPad and iPhone landscape
Fixes #2253
=> Fixes Navigation for double tap reaction on settings

Classes/Settings/SettingsViewController.swift
Fixes #2252 
Since we don't have navigation controller (on cold start), view source on settings opens Repo View Controller without a navigation controller. 😦 
But it will work fine if we have a nav controller in our stack. optional was helping us from crashing the app so far. I guess in a long run we might need to think in terms of moving to **Coordinators** for managing navigation inside the app to avoid issues like this. (probably better support for iPad and iPhone landscape)
=> Fixes navigation controller on "View Source" from settings

Classes/Notifications/NotificationCell.swift
Seems to fix the issue of the animation not always working
=> Keep read layer in front when animating inbox

Classes/Notifications/NotificationModelController.swift, Classes/Systems/Feed.swift
=> Proper fix to prevent double fetching from background

Setup.md
When following the steps for the setup of the project. The user is given steps to follow that could result in a leak of environment variables in the commit history. While those variables are not critical, I think it would show good development practices to people (especially people with not much experience with git).
=> Add steps in the setup to avoid commiting env variables to the repo

Classes/Issues/IssuesViewController.swift, Classes/PullRequestReviews/PullRequestReviewCommentsViewController.swift, Classes/Repository/RepositoryCodeBlobViewController.swift, Classes/Repository/RepositoryWebViewController.swift, Classes/Search/SearchViewController.swift, Classes/View Controllers/BaseListViewController.swift, Classes/Views/Constants.swift, Classes/Views/EmptyView.swift
This pr adds the proposed feature from #2214 
When loading fails a "Try Again" button apears right under, tapping this button does the equivelent of "Pulling to Refresh"
**Changes**
- Add "Try Again" button to `EmptyView`
- Add `EmptyViewDelegate` for retry button taps
- Add delegate and show retry button for every class using `EmptyView`
Here's a screenshot
=> Add "Try Again" button for EmptyView (#2214)

Classes/Settings/PushNotificationsDisclaimerViewController.swift, Classes/Settings/Settings.storyboard, Classes/Settings/SettingsViewController.swift, Freetime.xcodeproj/project.pbxproj
Show a disclaimer with details about how notifications work for both privacy and debugging if they aren't appearing.
=> Button to display Push Notification info in Settings

Classes/Notifications/NotificationModelController.swift, Local Pods/GitHubAPI/GitHubAPI/V3SubscribeThreadRequest.swift
=> Fetch subscription status and fix mutation

Classes/Notifications/NotificationCell.swift
=> Fix landscape read animation issue

Classes/Issues/IssuesViewController.swift, Classes/Issues/Labeled/IssueLabeledSectionController.swift, Classes/Issues/Labels/IssueLabelsSectionController.swift, Classes/Repository/RepositoryIssuesViewController.swift, Classes/Repository/RepositorySummarySectionController.swift, Classes/Repository/RepositoryViewController.swift, Classes/Utility/UIViewController+Routing.swift, Classes/View Controllers/UIViewController+PresentLabels.swift, Classes/View Controllers/UIViewController+Safari.swift, Freetime.xcodeproj/project.pbxproj
My second go at #2309 -> see that PR for vid. Functionality is the same. The difference is instead of passing the `GithubClient` around as a parameter in the LabelDetails model, used a protocol to route the tap to a view controller with access to `GithubClient`. Also, in order to do that, re-wired the IssueLabel SectionControllers to be the `MarkdownStyledTextViewDelegate` so that they could receive those taps and re-route them to the delegate w/ access to `GithubClient`.
=> Search for labels in app (take two)

Classes/Login/LoginSplashViewController.swift
Removes a deprecation warning for SFAuthentication because of using http
=> Use https url for login

Classes/Settings/SettingsViewController.swift
Also fix indentation on line 42.
=> Expand push settings info accessibility label

Classes/Issues/IssuesViewController.swift, Classes/Repository/RepositoryIssuesViewController.swift, Classes/View Controllers/UIViewController+PresentLabels.swift
Fixes #2332 and #2333 
Tested manually that: 
- Multi-word labels or labels w/ emoji's in them query correctly 
- tapping labels on pull requests pushes a list of Pull Requests, and tapping Issue labels pushes a list of Issues
=> cleans up issue labels query

Classes/Notifications/NotificationSectionController.swift, Classes/Systems/BadgeNotifications.swift
=> Clear push notifications on open

Classes/Notifications/NoNewNotificationsCell.swift
Connected to #2319 
I believe this will fix the constraint bugginess referenced in the screenshot in #2319 - to reproduce that, use a 5s phone in the simulator and go to landscape. 
I adjusted the constraints such that the "ReviewGithubAccess" btn will move closer to the bottom border if its superview is height-constrained. 
Bordered the contentView in blue and set arbitrary height constraints in following screenshots:
=> Update reivewGitHUbAccessBtn constraints

Classes/Settings/Settings.storyboard, Classes/Settings/SettingsViewController.swift
Adds "Try Beta" cell on Settings screen, On tap opens the testflight invite link in safari.
Closes #430
=> "Try Beta" on Settings

Classes/Settings/SettingsViewController.swift, Classes/Systems/Squawk+GitHawk.swift
Continuing from PR #2346 
Shows a Squawk message when user is already on beta and tapping "Try Beta" on settings screen.
This is how it looks. Feel free to change the colour of the Squawk or message.
=> Message on "Try Beta"  when already in TF

Classes/Issues/Comments/Markdown/String+DetectShortlink.swift, FreetimeTests/DetectShortlinkTests.swift
Connected to #2355  
Made a small change to the regex, and updated the unit tests to include the new test case and to accommodate testing more than one regex match in a single test string. 
I tested that this worked manually as well:
=> Fixes regex for consecutive shortlinks

Classes/History/PathCommitSectionController.swift, Classes/Issues/IssuesViewController.swift, Classes/Issues/Labeled/IssueLabeledSectionController.swift, Classes/Issues/Labels/IssueLabelsSectionController.swift, Classes/Repository/RepositoryIssuesViewController.swift, Classes/Systems/AppRouter/RepoRoute+RoutePerformable.swift, Classes/View Controllers/UIViewController+PresentLabels.swift
=> Lowercase issue/PR search string

Classes/Repository/RepositoryViewController.swift, Resources/Info.plist
.../more button when looking at repository has extra action when Working Copy is installed
to show or clone repository in this app.
This should address #2342
=> Allow showing/cloning repository in Working Copy when installed

Classes/Settings/DefaultReactionDetailController.swift, Classes/Settings/Settings.storyboard, Classes/Settings/SettingsViewController.swift
Closes #2356
Sry! oversight from mysids. This was introduced from my previous PR. 😦
=> Fixes Reaction emoji updates on split view

Classes/Issues/Comments/Markdown/String+DetectShortlink.swift, Freetime.xcodeproj/project.pbxproj, FreetimeTests/DetectShortlinkTests.swift
Connected to #2385 
This will allow dashes in owner and repository names - 
Updated screenshot: 
Added the above case to the unit tests. 
I also added some test cases to be explicit about allowing underscores before and after Issues. I was considering replacing `[a-zA-Z0-9]` with `\w` in a few places for brevity, but GitHub allows the underscore before and after an issue. Ie GitHub will recognize `_#1` and `#1_` as Issues and link them.
=> [2385] shortlink regex patch

Classes/Repository/RepositoryViewController.swift
This was lost after the switch from Tabman.
Allow the tabbar indicator to move while user swipes rather than a quick jump at the end.
=> Progressive swipe (Tabbar)

Classes/Settings/SettingsAccountsViewController.swift, Classes/Settings/SettingsViewController.swift, Classes/Systems/AppRouter/AppController.swift, Classes/Systems/AppRouter/AppSplitViewController.swift, Classes/Systems/AppRouter/SwitchAccountShortcutRoute+RoutePerformable.swift, Classes/Views/IssueTextActionsView+Markdown.swift, Local Pods/GitHubSession/GitHubSession/GitHubSessionManager.swift
Noticed this when testing. If you switch accounts the VCs would reset (deleting the switcher VC) and settings wouldn't change the selected account.
=> Better UX when switching accounts on iPad

Classes/Issues/IssuesViewController.swift, Classes/Issues/Preview/IssuePreviewViewController.swift, Classes/Notifications/NewFeaturesCell.swift, Classes/Notifications/NewFeaturesController.swift, Classes/Notifications/NewFeaturesSectionController.swift, Classes/Notifications/NotificationsViewController.swift, Classes/Views/Constants.swift, Classes/Views/IssueTextActionsView+Markdown.swift, Freetime.xcodeproj/project.pbxproj
- New repo here: https://github.com/GitHawkApp/Release-Notes/tree/master/versions
- Add version markdown with notes
- Able to skip display if notes request returns a 404
- Only displays once for new versions
- Follow-up: would be nice to maybe add a list of versions + notes (or just link to the notes repo/code)
cc @BasThomas
=> Show release notes UI in inbox when notable new features

Classes/View Controllers/SplitViewControllerDelegate.swift, FreetimeTests/SplitViewTests.swift
=> Tabbar hide fix

Classes/View Controllers/SplitViewControllerDelegate.swift, FreetimeTests/SplitViewTests.swift
Reverts GitHawkApp/GitHawk#2505
cc @Huddie tests failed after rebase w/ the bookmarks PR. Reverting for now just to get a green build on CI. Do you mind updating and resubmitting? Sorry for the churn!
=> Revert "Tabbar hide fix"

Classes/Repository/RepositoryCodeBlobViewController.swift
=> Fix code retry button and always enable options

Classes/Settings/SettingsViewController.swift
Right now the logout mentions that the bookmarks are removed during the logout process, but the `sessionManager` just signs out
fixes #2530
=> remove "remove bookmarks" part of the signout message

Classes/Issues/Comments/IssueCommentSectionController.swift
=> Fix bug where react UI unwinds itself

Classes/Bookmark/GitHubClient+Bookmarks.swift
=> Retain bookmark order when syncing

Classes/Settings/Settings.storyboard, Classes/View Controllers/SplitPlaceholderViewController.swift, Classes/Views/ClearAllHeaderCell.swift, Classes/Views/Styles.swift
Light gray was a little spazzy. This is much cleaner.
=> Use white background everywhere

Classes/Repository/RepositoryViewController.swift
A possible way to implement the issue mentioned in #2196
=> Add drop shadow to separate bar button and body text

Classes/Repository/RepositoryViewController.swift
Reverts GitHawkApp/GitHawk#2573
Fixes #2586
=> Revert "Add drop shadow to separate bar button and body text"

Classes/Systems/BadgeNotifications.swift
I was wondering why I never have any sound / vibration on notifications, while this is pleasant, we can let the user configure it in the notifications settings.
=> Adds sound option so device can vibrate and ring

Classes/Issues/Comments/Reactions/ReactionContent+ReactionType.swift, Classes/Issues/Comments/Reactions/ReactionsMenuViewController.swift, Classes/Issues/Comments/Reactions/UIMenuController+Reactions.swift, Classes/Settings/DefaultReactionDetailController.swift, Classes/Settings/Settings.storyboard, gql/API.swift, gql/schema.json
Closes #2605
Added two new emojis to GQL schema, emoji picker & default emoji selection screens. Moreover, split emoji picker cells into two rows, though the order of them is not preserved from Github Web UI.
|![simulator screen shot - iphone xr - 2019-01-20 at 11 13 14](https://user-images.githubusercontent.com/3721061/51437319-63240f80-1ca5-11e9-98c4-64de9a18abb1.png)|
|-|-|
1. Unknown emojis are still defaulted to 👍 , not which approach is better and if it's worth solving that at all;
2. Static UITableView for default emoji selection is a bit repetitive now, I suggest making dynamic list either as part of this PR or as a separate. Any thoughts?
=> Support rocket & eyes emojis

Classes/Repository/RepositoryCodeBlobViewController.swift, Classes/Views/CodeView.swift
=> Dismiss spinner only after code view is rendered

Classes/Settings/SettingsViewController.swift, Classes/Views/Styles.swift, Local Pods/GitHubAPI/GitHubAPI/GitHubAPIStatusRequest.swift
the "old" status page https://status.github.com is no deprecated and GitHub switched to a statuspage.io implementation with https://githubstatus.com. The page mentions the deprecation.
This PR switches the url to the new status page and changes the status API model for the new REST- response.
The new API replaced the `good` state with the state `none`. And has more fields, that are probably 
not relevant for the App.
Previous response:
```json
{"status":"good","last_updated":"2018-12-06T17:09:57Z"}
```
New response:
```json
{"page":{"id":"kctbh9vrtdwd","name":"GitHub","url":"https://www.githubstatus.com","time_zone":"Etc/UTC","updated_at":"2018-12-12T05:38:30.535Z"},"status":{"indicator":"none","description":"All Systems Operational"}}
```
New page in SafariVC:
fixes: #2546
=> switch from the now deprecated to the new status page

Classes/Repository/RepositoryCodeBlobViewController.swift, Classes/Repository/RepositoryCodeDirectoryViewController.swift, Classes/Repository/RepositoryImageViewController.swift, Classes/Repository/RepositoryViewController.swift
Changed all occurrences of "bullets-hollow" to "chevron-down" to be consistent with the "More Options" button image used in MergeButton.swift
Closes #2673
=> Fix for "Accessibility “bullets hollow” should be “more options” #2673

Classes/Issues/Merge/GithubClient+Merge.swift, Classes/Issues/Merge/IssueMergeSectionController.swift
I've implemented a haptic handler for a successful and unsuccessful merge results.
=> Add haptics for merge results

Classes/Labels/LabelsViewController.swift, Classes/Milestones/MilestonesViewController.swift, Classes/Notifications/Filter/InboxFilterReposViewController.swift, Classes/People/PeopleViewController.swift, Classes/Repository/RepositoryBranches/RepositoryBranchesViewController.swift
More specifically, in Labels, Milestones, People and Branches view controllers.
<details>
<summary>
Before:
</summary>
</details>
<details>
<summary>
After:
</summary>
</details>
=> Fix scroll indicator styles in menus

Classes/Repository/RepositoryBranches/GitHubClient+RepositoryBranches.swift, Classes/Repository/RepositoryBranches/RepositoryBranchesViewController.swift, gql/API.swift, gql/RepoBranches.graphql
Closes (#2587)
Possibly quite an edge case to have more than 50 branches but it was fun working w/ GQL and pagination implementation here 🎆 
Follows pagination convention from `RepositoryIssuesViewController.swift` & `RepositoryClient.swift`, though I didn't understand why `RepoSearchPagesQuery` conforms to `RepositoryQuery` protocol instead of having extension for `RepoSearchPagesQuery.Data`.
|![simulator screen shot - iphone xr - 2019-01-21 at 14 33 59](https://user-images.githubusercontent.com/3721061/51474991-c0918c80-1d89-11e9-9ce0-3ab69e0cd0e2.png)|
|-|
=> Pagination for repo branches list

Gemfile.lock
Took forever to figure this out. Bitrise has been broken since 2/22. This commit broke it by updating Bundler to a version that conflicts w/ the fastlane/deploy Bitrise step.
https://github.com/GitHawkApp/GitHawk/commit/f0a62aa7d28a61bf8e15b741052067dd3fff83ee#diff-e79a60dc6b85309ae70a6ea8261eaf95
Testing deploying TF build from this PR.
=> Fix Bundler conflict in Bitrise

Classes/Settings/SettingsViewController.swift
This is a fix for https://github.com/GitHawkApp/GitHawk/issues/2743 and https://github.com/GitHawkApp/GitHawk/issues/2643.
Reading through the issues, It looks like the crash only occurred on iPads and that's where I was able to reproduce it. It's the notorious `popoverPresentationController` that's always too easy to miss. 🧐
=> Fix logout crash

Classes/Issues/IssueManagingContextController.swift, Classes/Issues/IssuesViewController.swift
This is a fix for https://github.com/GitHawkApp/GitHawk/issues/2229.
It builds on work and code review comments in https://github.com/GitHawkApp/GitHawk/pull/2294. `IssueManagingContextControllerDelegate` is notified of changes to the button's visibility so that it can update its layout (in this case, update collection view's inset) - I was hoping this would make the update more explicit. The inset itself is calculated using the button's `height` instead of relying on `Styles.Sizes.tableCellHeight`.
Let me know if any of this is not clear or could be improved. I'm happy to try the other approaches suggested in the old pull request - a) moving the button hiding out into the VC, b) giving the manage controller a reference to the scroll view or c) putting a transparent view with the …
=> Fix extra space at the bottom of pull request status view (#2229)

Classes/Issues/Referenced/IssueReferencedModel.swift, Classes/Issues/Referenced/IssueReferencedSectionController.swift
This fixes #2260. 🤞 
When user taps `IssueReferencedCell`, 2 competing delegates can be notified - 
1. `UICollectionViewDelegate`
2. `MarkdownStyledTextViewDelegate`
When both delegates are notified (for example when user taps username in a referenced issue), `UICollectionViewDelegate` (`IssueReferencedSectionController`) will push a new `IssuesViewController` :
https://github.com/GitHawkApp/GitHawk/blob/f28b119009e96a1a6dd53ae0e90b7beefc58833c/Classes/Issues/Referenced/IssueReferencedSectionController.swift#L39
and `MarkdownStyledTextViewDelegate` (`IssuesViewController`) will present a profile via `SFSafariViewController` :
https://github.com/GitHawkApp/GitHawk/blob/80d1255401f9d5b53472dd34a3543d3acdf6da1c/Classes/Utility/UIViewController%2BRouting.swift#L21
Since …
=> Fix pushing Issues VC when user taps on username in referenced issues
