GitHawkApp/GitHawk

Classes/Notifications/NotificationsViewController.swift

https://github.com/rnystrom/Freetime/issues/44
I’m interested in contributing to the project. Just trying to get my feet wet with this one.

Disable mark all button if all visible notifications are read

---

Classes/Models/App.swift
Classes/Models/Authorization.swift
Classes/Models/Notification.swift
Classes/Models/Organization.swift
Classes/Models/Permission.swift
Classes/Models/Repository.swift
Classes/Models/Subject.swift
Classes/Models/User.swift
Classes/Other/Secrets.swift
Classes/Systems/GithubSessionManager.swift
Classes/Systems/GithubUserSession.swift
Classes/Systems/StatusBar.swift
Classes/Views/Strings.swift
Classes/Views/Styles.swift

This prevents you from incidentally creating an instance.
See https://github.com/rnystrom/Freetime/commit/8feaaa3f641b3202809655cdee92193860b25776#commitcomment-23029752

Change struct with static funcs / lets to enum

---

Classes/Settings/SettingsReportSectionController.swift
Classes/Utility/Device+Model.swift
Classes/Utility/UIDevice+Model.swift
Freetime.xcodeproj/project.pbxproj
Resources/Info.plist

Not sure what message you want in the template, so happy to change!
Related to #130 
Output is like this:

Add version info to report a bug template

---

Classes/Login/GithubClient+AccessToken.swift
Classes/Login/LoginSplashViewController.swift
Classes/Login/OauthLogin.storyboard
Classes/Systems/Alamofire+GithubAPI.swift
Classes/Systems/GithubSessionManager.swift
Classes/Systems/GithubUserSession.swift
Sample/Samples.swift

Take 2 (take 1 [here](https://github.com/rnystrom/Freetime/pull/134)) of the functionality to log in with a personal access token. The UI now looks like this:
Fixes https://github.com/rnystrom/Freetime/issues/111. Any and all feedback welcome!

Implement login with personal access token

---

README.md

The copy is from http://freetime-app.com :)

[readme] improve

---

README.md

Ref https://twitter.com/BasThomas/status/896820749318705154

Add TestFlight info to Readme

---

Classes/Repository/Empty/RepositoryEmptyResultsType.swift
Classes/Repository/RepositoryViewController.swift

Fixes #303 
In case if anyone has a better option for icon or text please do let me know.

Adds empty state when no readme for repository

---

Classes/Repository/RepositoryViewController.swift

Fixes #306 
Adds "More Options" navigation item to repository view controller with below actions.
- Sent To 
- Open in Safari
- View Owner's Profile

Adds "More Options" to repository

---

Classes/Issues/Comments/Reactions/IssueReactionCell.swift
Classes/Notifications/NotificationCell.swift
Classes/Notifications/NotificationNextPageCell.swift
Classes/Repository/Empty/RepositoryEmptyResultsCell.swift
Classes/Repository/RepositorySummaryCell.swift
Classes/Search/SearchNoResultsCell.swift
Classes/Search/SearchRepoResultCell.swift
Resources/Info.plist

Fixes #329  
@Sherlouk: how can I add a compiler flag to the project to check? Can only seem to find how to add one to a specific file.

Prefer interpolation over concatenation

---

Classes/Issues/IssuesViewController.swift
Classes/Repository/RepositoryViewController.swift
Resources/Info.plist

Fixes #357 
Now we can escape the alertsheet!

Add cancel button to repository more options

---

.gitignore
README.md
package-lock.json
package.json

Addresses #282.
I figured the best way to do this was to use `yarn` to pin a specific version, let me know if you think it's overkill. 🤔

Add dependency to Apollo-codegen

---

Classes/Issues/IssuesViewController.swift
Classes/Login/LoginSplashViewController.swift
Classes/Notifications/NotificationNavigation.swift
Classes/Notifications/NotificationsViewController.swift
Classes/Repository/RepositoryViewController.swift
Classes/Settings/SettingsAccountsViewController.swift
Classes/Settings/SettingsViewController.swift
Classes/View Controllers/CreateProfileViewController.swift
Classes/View Controllers/UIViewController+Alerts.swift
Classes/View Controllers/UIViewController+Safari.swift

- Update `onTintColor` of all `UISwitch`es to `Green.medium`
- Update `tintColor` of all `UIAlertController`s to `Blue.medium`
- Update `preferredControlTintColor` of all `SFSafariViewController`s to `Blue.medium`
I created an `SFSafariViewController` factory which performs the HTTP scheme check, and also applies the `preferredControlTintColor`. I’ve updated every initializer of `SFSafariViewController` to use this factory instead, so that the styling only needs to be set in one place. In doing so, I’ve had to force unwrap in `CreateProfileViewController` and `NotificationNavigation` to preserve the method signatures, but let me know if you want this handled better.
I have also created a similar factory which configures the `tintColor` for `UIAlertController`.
I’ve created these factories …

[413] Use shared colours for standard UI components

---

Freetime.xcodeproj/project.pbxproj

I just realized the Apollo bass script doesn't handle local binaries, so we need to add this folder to the $PATH env var.

Add node bin to path before looking for apollo

---

Classes/Issues/Comments/IssueCommentSectionController.swift
Classes/Issues/Review/IssueReviewSectionController.swift

Fixes #388 
Am I missing something here?

Fixes referenced issue view controller being pushed without nav bar

---

.gitignore
docs/README.md
docs/_posts/2017-09-26-Accessibility-in-GitHawk.md

And also
- Add Jekyll stuff to `.gitignore`.
- Add simple `README` to explain how to get started on adding a blog post

Add blogpost on accessibility

---

Classes/Notifications/NotificationSectionController.swift

Fixes navigation bar for issues/PR when pushed from notifications

---

Classes/Notifications/NotificationsViewController.swift

https://github.com/rnystrom/GitHawk/commit/49c4bfaf9afc0c6a54a889af3656d73aa9745ab8#commitcomment-24660022
Super minor!

Invert guard for improved readability

---

Classes/Notifications/NoNewNotificationsCell.swift
Resources/Info.plist

Combine inbox zero views into one accessibility item

---

Classes/Repository/RepositoryViewController.swift
Classes/Search/SearchViewController.swift

Added iOS 11 searchController UINavigationItem

---

Classes/Utility/AlertAction.swift
Resources/Info.plist

This makes the actions colored red, to indicate a) they have consequences and b) to make them stand out more from other actions

Make impactful actions destructive

---

Classes/New Issue/NewIssue.storyboard
Classes/New Issue/NewIssueTableViewController.swift

Enable/Disable New issue submit button based on title text

---

Classes/Utility/AlertAction.swift

Change "Open Repo" to "View Repo"

---

Classes/Systems/AppDelegate.swift
Classes/Systems/RootNavigationManager.swift
Classes/Systems/ShortcutHandler.swift
Freetime.xcodeproj/project.pbxproj
Resources/Info.plist

Added shortcuts for:
* Search
* Switch accounts
**Note:**
I haven't tried out the switch account item since i only have one account so @rnystrom please try that first. 
#342

3D Touch shortcuts

---

Classes/Issues/IssuesViewController.swift
Classes/Utility/AlertAction.swift
Resources/Info.plist

Closes #143
Closes #557
Got to keep PR count >= 10 😉

Make lock action destructive, Append issue type

---

Classes/Views/UICollectionViewCell+SafeAreaContentView.swift

Only use left and right safe insets for UICollectionViewCell contentView

---

Classes/Issues/Comments/IssueCommentModel.swift
Classes/Issues/Comments/IssueCommentSectionController.swift
Classes/Issues/EditComment/EditCommentViewController.swift
Classes/Issues/EditComment/GithubClient+EditComment.swift
Classes/Issues/GithubClient+Issues.swift
Classes/Issues/Issue+IssueType.swift
Classes/Issues/IssueViewModels.swift
Classes/Issues/IssuesViewController.swift
Classes/Issues/PullRequest+IssueType.swift
Classes/New Issue/NewIssueTableViewController.swift
Classes/Notifications/NotificationsViewController.swift
Classes/View Controllers/UIViewController+LoadingIndicator.swift
Freetime.xcodeproj/project.pbxproj
Resources/Info.plist

Looks like this is working! Going to send out a TestFlight build w/ this. Will merge tomorrow!
Fixes #205

Finish wiring up edit comments

---

Classes/New Issue/NewIssueTableViewController.swift
Classes/Systems/Toast+GitHawk.swift
Classes/Systems/Toast.swift
Resources/Info.plist

Toast mounts to UIWindow

---

Local Pods/SlackTextViewController/Source/SLKTextViewController.m

Fixes #583 
Applied patch from Slack PR, works!

iPhone X support for Slack text view

---

Freetime.xcodeproj/project.pbxproj
Resources/Info.plist
tools/bump_build_number.sh

Following [this post](http://www.mokacoding.com/blog/automatic-xcode-versioning-with-git/). Adding commit hash to a custom key in Info.plist so we can display + link to it later in settings alongside the version and build #.

CFBundleVersion set to commit count

---

Freetime.xcodeproj/project.pbxproj
FreetimeTests/IssueLabelCellTests.swift
FreetimeTests/Mocks/MockSearchEmptyViewDelegate.swift
FreetimeTests/Search Tests/SearchEmptyViewTests.swift
FreetimeTests/SignatureTests.swift

Let's start that coverage % creep up 👍

Miscellaneous unit tests

---

Classes/Search/SearchRecentCell.swift
Classes/Search/SearchRecentSectionController.swift
Classes/Search/SearchRecentStore.swift
Classes/Search/SearchViewController.swift
Classes/Views/Constants.swift

User can delete individual searches in the search controller

---

Classes/Systems/Feed.swift

Remove unused UICV subclass

---

tools/bump_build_number.sh

Disable git hash from build script

---

Local Pods/SlackTextViewController/Source/SLKTextView+SLKAdditions.m

Avoid KVO bugs changing content offset

---

Classes/Repository/RepositoryDetails.swift
Classes/Search/SearchQuery.swift
Classes/Search/SearchRecentCell.swift
Classes/Search/SearchRecentSectionController.swift
Classes/Search/SearchRecentStore.swift
Classes/Search/SearchRecentViewModel.swift
Classes/Search/SearchResultSectionController.swift
Classes/Search/SearchViewController.swift
Classes/Systems/Debouncer.swift
Freetime.xcodeproj/project.pbxproj

Recently viewed repos

---

Classes/Repository/RepositoryDetails.swift
Classes/Search/GithubClient+Search.swift
Classes/Search/SearchQuery.swift
Classes/Search/SearchRecentCell.swift
Classes/Search/SearchRecentSectionController.swift
Classes/Search/SearchRecentStore.swift
Classes/Search/SearchRecentViewModel.swift
Classes/Search/SearchResultSectionController.swift
Classes/Search/SearchViewController.swift
Classes/Systems/Debouncer.swift
Classes/Utility/IsCancellationError.swift
Freetime.xcodeproj/project.pbxproj
FreetimeTests/Search Tests/SearchRecentStoreTests.swift

Enables search while typing. 
Pointing at my other branch until it gets merged to master since it relies on some of those changes. 
Closes #596

User can receive search results while typing

---

Classes/Search/SearchViewController.swift
Classes/Section Controllers/SearchBar/SearchBarCell.swift
Resources/Info.plist

Fixes #610 
Ended up doing this when the keyboard will hide, so it happens at that point immediately. Thought that would make more sense then doing so when the view will disappear.

Resign first responder when hiding keyboard

---

Classes/Section Controllers/SearchBar/SearchBarCell.swift

Gives the return key a purpose and also feels more natural(at least for me) than scrolling to dismiss.

Add done return key type that dismisses keyboard for notifications/issues/pr search

---

Classes/Notifications/NotificationsViewController.swift
Classes/View Controllers/UIViewController+LoadingIndicator.swift

Swapped Bar Button Items

---

Classes/Settings/Settings.storyboard
Classes/Settings/SettingsAccountsViewController.swift
Classes/Settings/SettingsViewController.swift

Ref #624 
Should do the same (again) with bug reporting, but it's a bit more tricky.

Open accounts in detail on iPad

---

Classes/Notifications/NotificationsViewController.swift

Auto merging so I can get a TestFlight build out

Disable updating tab and badge when on Archives

---

Classes/Repository/RepositorySummarySectionController.swift

Ceiling final height of repo issue cells

---

Classes/Search/SearchRecentHeaderCell.swift
Classes/Utility/AlertAction.swift

Change "Clear" to "Clear All"

---

Classes/Image Upload/ImageUploadTableViewController.swift
Classes/Views/Constants.swift
Freetime.xcodeproj/project.pbxproj
Resources/Info.plist

Fixes #662 
Fixes #665 
Fixes #673 
#664 would require a fair bit more work to remove the borders as it uses a UITableView in the grouped style. Would have to redo quite a bit to not use a UITableView for that bit

Replace image upload images with text, hook up cancel button

---

Classes/Systems/ShortcutHandler.swift
Classes/Views/Constants.swift

3D touch short cut item for bookmarks tab

---

Classes/Bookmark/BookmarksViewController.swift

Fixes scroll to top for bookmarks screen

---

Classes/Search/SearchRecentStore.swift
Classes/Search/SearchViewController.swift
Classes/Systems/Debouncer.swift
FreetimeTests/Search Tests/SearchRecentStoreTests.swift

Preventing the search race condition instead of responding to it

---

Classes/Views/Constants.swift

Standardized sign-in/out copy

---

Classes/Utility/AlertAction.swift

As discussed [here](https://github.com/rnystrom/GitHawk/pull/678#issuecomment-338507125) and [here](https://github.com/rnystrom/GitHawk/pull/601#issue-266518955).

Rename "Add to Bookmark" to simply "Bookmark"

---

Classes/Bookmark/BookmarksViewController.swift

Removed bookmark cell dividers, added bg color

---

Classes/Section Controllers/LoadMore/LoadMoreCell.swift

Gives some indication that load more has been pressed.

Adds light gray text color on selection of LoadMoreCell

---

Classes/New Issue/NewIssueTableViewController.swift

Focus title field when creating a new issue

---

Classes/Systems/ForegroundHandler.swift

Delay refresh after warm start triggers reload

---

Classes/Search/SearchRecentCell.swift

Changes search recent image view tint as blue

---

Classes/Issues/EditComment/EditCommentViewController.swift
Classes/Issues/IssuesViewController.swift
Classes/New Issue/NewIssueTableViewController.swift
Classes/Views/TextActionsController.swift

Closes #765 
Using real username instead of `Sherlouk` 😆

Fixes User name on image upload

---

Classes/New Issue/NewIssueTableViewController.swift

New issue title first responder only when loading the view

---

Classes/Issues/IssuesViewController.swift
Classes/View Controllers/UINavigationItem+TitleSubtitle.swift
Freetime.xcodeproj/project.pbxproj

Making room. I'm going to move bookmark actions to a nav bar item. Prepping some action cleanup and UI polish.
What do you like, thin + dark or bold + light on the subtitle? I lean bold+light (bold+dark isn't enough contrast).

Add title/subtitle header style and use for Issues

---

Classes/Repository/RepositoryCodeDirectoryViewController.swift

Improve code browsing accessibility

---

Classes/Systems/ShortcutHandler.swift

Fixes Bookmark quick action icon

---

Classes/Bookmark/BookmarkStore.swift
Classes/Bookmark/BookmarksViewController.swift
Classes/Issues/IssuesViewController.swift
Classes/Repository/RepositoryViewController.swift
Classes/Utility/AlertAction.swift
FreetimeTests/BookmarkStoreTests.swift

Closes #695 
I don't have an additional Github user account to test this. However, wrote some tests for it.

Bookmarks per user account

---

Classes/Bookmark/AlertAction+Bookmark.swift
Classes/Bookmark/BookmarkStore.swift
Classes/Bookmark/BookmarksViewController.swift
Classes/Issues/IssuesViewController.swift
Classes/Repository/RepositoryViewController.swift
Classes/Systems/GithubClient.swift
Classes/Utility/AlertAction.swift
Freetime.xcodeproj/project.pbxproj

Followup from #738
- Dependency inject a single object
- Don't init if token doesn't exist
- Move action to helper func so no duped code
cc @rizwankce

Inject bookmarks, cleanup

---

Classes/Issues/Comments/Html/IssueCommentHtmlCell.swift

Fixes #629 
Pain in the ass, might require opening a radar.

Prevent nested webviews using safe area on layout

---

Classes/Bookmark/BookmarkStore.swift
Classes/Bookmark/BookmarksViewController.swift
Freetime.xcodeproj/project.pbxproj
FreetimeTests/BookmarksStoreListenerTests.swift

Closes #773 
Tried announcer pattern, Please review

Update bookmarks without reloading view

---

Classes/Image Upload/ImageUpload.storyboard
Classes/Image Upload/ImageUploadTableViewController.swift

Add “optional” in the title's placeholder.
And since the message is a TextView I added UITextViewDelegate methods to change text and textColor when needed.
ref #771

Specify that image upload title and message are optional

---

Classes/Models/NotificationResponse.swift
Classes/Notifications/Notification+NotificationViewModel.swift
Classes/Notifications/NotificationClient.swift
Classes/Notifications/NotificationsDataSource.swift
Freetime.xcodeproj/project.pbxproj

Rename `Notification` to `NotificationResponse`

---

Classes/Issues/Comments/Html/IssueCommentHtmlCell.swift

leftover fixes from #600, sorry for the delay 😇

Fixes <detail> styling.

---

Classes/Notifications/NotificationsViewController.swift
Classes/Repository/RepositoryIssuesViewController.swift
Classes/View Controllers/BaseListViewController.swift

Mutations was a little gross. Cleans that up a bit so we're always fetching the latest model from the cache when something changes.

Better FlatCache usage in notifications

---

Classes/Bookmark/BookmarksViewController.swift
Classes/Issues/IssuesViewController.swift
Classes/Notifications/NotificationsViewController.swift
Classes/Repository/RepositoryViewController.swift

Remove iOS 11 navigation titles

---

Classes/Search/SearchViewController.swift

Consistent back nav title from search

---

Classes/Issues/IssuesViewController.swift
Classes/Repository/RepositoryDetails.swift
Classes/Repository/RepositoryViewController.swift
Classes/Utility/AlertAction.swift

Refactor alert titles

---

Classes/Repository/RepositoryViewController.swift

Repo uses title/subtitle

---

Classes/Bookmark/BookmarkStore.swift
FreetimeTests/BookmarkStoreTests.swift

Closes #822 
Learnt some nifty details. Oversight from my side. Hope I'm not alone

Sorted/Ordered Bookmarks

---

Classes/Repository/RepositoryCodeDirectoryCellExtension.swift
Classes/Repository/RepositoryCodeDirectoryViewController.swift
Freetime.xcodeproj/project.pbxproj
Settings.bundle/com.mono0926.LicensePlist.plist
gql/API.swift

This fixes #749, sorry I've messed up the other Pull request

Add Cell setup code to an StyledTableCell Extension

---

Classes/Bookmark/BookmarkCell.swift
Classes/Bookmark/BookmarksViewController.swift
Freetime.xcodeproj/project.pbxproj

Closes #812 
Guess #720 causes some issues with bookmark cell dynamic sizes. This will fix that and a bonus point it will fix crash on swipe to delete and a custom bookmark cell.

Bookmark cell dynamic size and fix swipe to delete crash

---

Classes/Issues/Comments/IssueCommentSectionController.swift

Changes on issue comment alert title and actions

---

Classes/Utility/DeleteSwipeAction.swift

Removed trash icon from DeleteSwipeAction

---

Classes/Utility/UIDevice+Model.swift

Add:
* iPhone 8
* iPhone 8 Plus
* iPhone X
* iPad Pro

UIDevice: Add new models of iPhone and iPad Pro

---

Classes/Views/FeedRefresh.swift

Adjust UIRefreshControl z position so always behind cells

---

Classes/Search/SearchViewController.swift

Pushing from Search should always be animated

---

Classes/Issues/Comments/Details/IssueCommentDetailCell.swift
Classes/Issues/Comments/Images/IssueCommentImageCell.swift

Invert colors for comment images, comment profile images

---

Classes/Bookmark/BookmarkModel.swift
FreetimeTests/BookmarkStoreTests.swift

Fix bookmarks tests

---

Classes/Issues/Comments/IssueCommentSectionController.swift
Classes/PullReqeustReviews/GithubClient+PullRequestReviewComments.swift

Append a tail model for border on last PR comment in a thread

---

Classes/Bookmark v2/BookmarkCell.swift
Classes/Bookmark v2/BookmarkSectionController.swift
Classes/Bookmark v2/BookmarkStore.swift
Classes/Bookmark v2/BookmarkViewController.swift
Classes/Bookmark v2/BookmarkViewModel.swift
Classes/Issues/Labels/IssueLabelSummaryCell.swift
Classes/Utility/AlertAction.swift
Classes/Utility/AlertActionBuilder.swift
FreetimeTests/Bookmark Tests/BookmarkViewModelTests.swift

- Replaced "// MARK: -" with "// MARK:"
- Added final to classes
- Added newlines for readability
- Computed and stored diffIdentifier of BookmarkViewModel
- Removed NSObject from BookmarkViewModel inheritance
- Moved icon logic to the configure block of the BookmarkCell

Picked up the easy bits of Ryan's review #865

---

Classes/Notifications/NotificationsViewController.swift

Hides "Mark All" button when there is no "Unread" message

---

Classes/Issues/EditComment/EditCommentViewController.swift
Classes/Issues/IssuesViewController.swift

Enable image upload for comments

---

Classes/Bookmark v2/BookmarkViewController.swift
Classes/Issues/IssuesViewController.swift
Classes/Issues/Preview/IssuePreviewViewController.swift
Classes/Search/SearchViewController.swift
Classes/Systems/Feed.swift

Fixes #890 
Gonna test this out locally for a day

Use ListCollectionViewLayout for VC lists

---

Classes/Issues/Comments/Images/IssueCommentImageCell.swift
Classes/Systems/ImageCellHeightCache.swift
Classes/Views/BoundedImageSize.swift
Freetime.xcodeproj/project.pbxproj

Comment cell images don't scale to fit

---

Classes/Issues/Comments/Details/IssueCommentDetailCell.swift
Classes/Views/Styles.swift

Increased tap target for ... buttons

---

Classes/Settings/Settings.storyboard
Classes/Settings/SettingsViewController.swift

Fixes #904 
Any reason why that cell is not a `StyledTableCell`?

Open GitHub Status when tapping cell

---

Classes/Bookmark v2/BookmarkViewController.swift
Classes/Issues/IssuesViewController.swift
Classes/Issues/Preview/IssuePreviewViewController.swift
Classes/Search/SearchViewController.swift
Classes/Systems/Feed.swift

Revert "Use ListCollectionViewLayout for VC lists"

---

Classes/Bookmark v2/BookmarkViewController.swift
Classes/Issues/EditComment/EditCommentViewController.swift
Classes/Search/SearchViewController.swift
Classes/Section Controllers/SearchBar/SearchBarCell.swift
Classes/Systems/ScrollViewKeyboardAdjuster.swift
Classes/Views/UISearchBar+Keyboard.swift
Freetime.xcodeproj/project.pbxproj

Noticed some copy/paste. This should speed up anyone working on stuff that requires handling the kb. Also adds animation.

Add keyboard helpers to remove duped code

---

Classes/Views/EmptyView.swift

Empty view background clear

---

Classes/Bookmark v2/BookmarkNavigationController.swift
Classes/Issues/IssuesViewController.swift
Classes/Repository/RepositoryViewController.swift
Classes/View Controllers/UIPopoverPresentationController+SourceView.swift
Classes/Views/Styles.swift
Classes/Views/UIBarButtonItem+TightSpacing.swift
Freetime.xcodeproj/project.pbxproj

Tightened right bar items

---

Classes/Issues/GithubClient+Issues.swift

Fix incorrect state sent to status API

---

Classes/Settings/SettingsViewController.swift

Open review access in Safari.app on iOS 11

---

Local Pods/SlackTextViewController/Source/SLKTextViewController.m

Scroll all the way to the bottom when keyboard is displayed

---

Local Pods/SlackTextViewController/Source/SLKTextViewController.m

Fix text view showing while loading

---

Classes/Systems/ShortcutHandler.swift

Remove Search subtitle from shortcut

---

Classes/Bookmark v2/BookmarkViewController.swift
Classes/Issues/IssuesViewController.swift
Classes/Issues/Preview/IssuePreviewViewController.swift
Classes/Search/SearchViewController.swift
Classes/Systems/Feed.swift
Classes/Views/IGListCollectionViewLayout+GitHawk.swift
Classes/Views/UICollectionViewLayout+Orientation.swift
Freetime.xcodeproj/project.pbxproj

Restoring this PR, found a way to invalidate for orientation changes

Use IGListCollectionViewLayout

---

Classes/Issues/EditComment/EditCommentViewController.swift
Classes/Issues/IssuesViewController.swift
Classes/New Issue/NewIssueTableViewController.swift

Define viewController for image upload to present chooser/upload UI

---

Classes/Image Upload/ImageUpload.storyboard
Classes/Image Upload/ImageUploadTableViewController.swift

I felt guilty for breaking images (again) so I'll give you a little present 🎁 seems fair right?
Closes #760

Allow user to preview image upload using NYTPhotoViewer

---

Classes/Models/Subject.swift

Remove last comment URL from the required subject model

---

Resources/Info.plist

Bump version to 1.12.1

---

Resources/Info.plist

1.12.1 shipped, prep next version

Bump to version 1.13.0

---

Classes/Issues/GithubClient+Issues.swift
Classes/Issues/IssuesViewController.swift

Fixes #963
Sending out a TF build from this branch

Use collab permissions endpoint to check collab status

---

Classes/Search/SearchRecentCell.swift

Search UI consistent with app

---

Classes/Issues/GithubClient+Issues.swift

Add optimistic label events

---

Classes/Issues/IssuesViewController.swift

New comments use FlatCache mutation system

---

Classes/Bookmark v2/BookmarkCell.swift
Classes/Bookmark v2/BookmarkViewModel.swift
FreetimeTests/Bookmark Tests/BookmarkViewModelTests.swift

Bookmark cell refactor for consistent UI

---

Classes/Issues/IssuesViewController.swift

Move neck load cell beneath root comment

---

Classes/Labels/Labels.storyboard

Done style

---

Classes/Issues/Managing/IssueManagingSectionController.swift

Prevent tapping managing cells while animating

---

Classes/Systems/NSAttributedStringSizing.swift

Dump bitmap caches on memory warning

---

Freetime.xcodeproj/project.pbxproj

Tests were failing to build after merging #809

Fix unit tests

---

Classes/Issues/Assignees/IssueAssigneeSummaryModel.swift
Classes/Issues/Comments/Details/IssueCommentDetailCell.swift
Classes/Issues/GithubClient+Issues.swift
Classes/Issues/Managing/IssueManagingSectionController.swift
Classes/People/GithubClient+People.swift
Classes/People/People.storyboard
Classes/People/PeopleCell.swift
Classes/People/PeopleViewController.swift
Classes/Views/UIImageView+Avatar.swift
Freetime.xcodeproj/project.pbxproj

Add and remove assignees

---

Classes/Labels/LabelsViewController.swift

Sort labels alphabetically

---

Classes/Issues/IssueTextActionsView.swift
Classes/Views/IssueTextActionsView+Markdown.swift

Add accessibility labels to markdown bar operations

---

Classes/Systems/Secrets.m
Freetime.xcodeproj/project.pbxproj

Used this resource to finish getting this working:
https://fabiancanas.com/blog/2014/9/1/keeping-private-api-keys-private.html
Fixes #1031

Fix constants in config

---

Freetime.xcodeproj/project.pbxproj

Fixes #1038.
If someone can double-check this by recloning the repo and setting it up + trying to login, 💯

Generate xcconfigs before checking lockfile

---

Classes/Issues/EditComment/EditCommentViewController.swift

Fixes #976.
Followed the same thing we do when [creating a new issue](https://github.com/rnystrom/GitHawk/blob/master/Classes/New%20Issue/NewIssueTableViewController.swift#L202-L204).

Disable the right item editing a comment to an empty one

---

Classes/Systems/Secrets.m

Use actual imgur key

---

Classes/Issues/EditComment/EditCommentViewController.swift
Classes/New Issue/NewIssueTableViewController.swift

Add magic tap to saving comment/sending issue

---

Classes/Issues/Issue+IssueType.swift
Classes/Issues/PullRequest+IssueType.swift
Classes/Issues/Referenced/IssueReferencedCell.swift
gql/API.swift
gql/IssueOrPullRequest.graphql
gql/schema.json

Add support for cross reference events

---

Classes/Issues/Comments/Markdown/MarkdownAttribute.swift
Classes/Issues/Issue+IssueType.swift
Classes/Issues/ReferencedCommit/IssueReferencedCommitCell.swift
Classes/Issues/ReferencedCommit/IssueReferencedCommitModel.swift
Classes/Issues/ReferencedCommit/IssueReferencedCommitSectionController.swift
Classes/Models/CommitDetails.swift
Classes/View Controllers/UIViewController+AttributedStringViewDelegate.swift
Classes/Views/AttributedStringView.swift
Freetime.xcodeproj/project.pbxproj

Reference commit cells use attr string cell

---

Classes/Issues/ReferencedCommit/IssueReferencedCommitSectionController.swift
Classes/Systems/Alamofire+GithubAPI.swift
Classes/Systems/GithubSessionManager.swift

Followup from #1068
Also removed sample code from #1065 (I didn't build the project 🙈 )

Reference commit cell uses text height

---

Classes/Issues/Issue+IssueType.swift
Classes/Issues/MilestoneEvent/IssueMilestoneEventCell.swift
Classes/Issues/MilestoneEvent/IssueMilestoneEventModel.swift
Classes/Issues/MilestoneEvent/IssueMilestoneEventSectionController.swift
Classes/Issues/PullRequest+IssueType.swift
Classes/Milestones/GithubClient+Milestones.swift

Milestone event cells use attributed text system

---

Classes/Systems/NSAttributedStringSizing.swift

Only keep one bitmap cache at a time

---

Classes/Search/SearchRecentSectionController.swift

Search cell shares common height

---

Classes/Issues/Files/IssuePatchContentViewController.swift
Classes/Repository/RepositoryCodeBlobViewController.swift
Classes/Views/CodeView.swift
Freetime.xcodeproj/project.pbxproj

- New `CodeView` to standardize how we display code
- Will extend w/ Highlightr once that's in
- Use this view for file patches and repo code

Share code text view with repo and issue

---

Classes/Issues/GithubClient+Issues.swift
Classes/Issues/Issue+IssueType.swift
Classes/Issues/Labeled/IssueLabeledModel.swift
Classes/Issues/PullRequest+IssueType.swift
Classes/Views/CodeView.swift

Warm label event size caches

---

Classes/Bookmark v2/BookmarkCell.swift
Classes/Search/SearchRecentCell.swift
Classes/Search/SearchRepoResultCell.swift
Classes/Views/SelectableCell.swift

Closes #1079 #1080 
Couldn't contribute more for past weeks bcz moved to China (till end of Jan). probably take small tasks in upcoming days! 👍

Make Bookmark cell and Search Recent cell accessible

---

Classes/Issues/Comments/Html/IssueCommentHtmlCell.swift
Classes/Issues/Comments/IssueCommentSectionController.swift
Classes/Issues/IssueCommentModelHandling.swift
Classes/Issues/Preview/IssuePreviewSectionController.swift
Classes/Issues/Review/IssueReviewSectionController.swift
Classes/Repository/RepositoryReadmeSectionController.swift
Classes/Systems/PhotoViewHandler.swift

Open fullscreen images when tapping web view <img>

---

Classes/Issues/Managing/IssueManagingActionCell.swift
Classes/Issues/Managing/IssueManagingExpansionCell.swift

Accessibility for manage buttons

---

Classes/Issues/Labeled/IssueLabeledModel.swift
Classes/Issues/Labeled/IssueLabeledSectionController.swift
Classes/Systems/NSAttributedStringSizing.swift

Fixes #1110
Dropping border in favor of simplicity

Clean label background drawing

---

Classes/Issues/Issue+IssueType.swift
Classes/Issues/PullRequest+IssueType.swift
Classes/Issues/Referenced/IssueReferencedCell.swift
Classes/Issues/Referenced/IssueReferencedModel.swift
Classes/Issues/Referenced/IssueReferencedSectionController.swift

Fixes #1055, #1096
- There's a tapping bug, filed #1125.
- I'm not sold on the gray and bold setup here. Maybe the issue title should be a larger size?
Here's GitHub for reference:

Show reference author and convert to AttributedStringCell

---

Classes/Bookmark v2/BookmarkCell.swift

Layout bookmark cell on settings change

---

Classes/Issues/Comments/Markdown/MarkdownAttribute.swift
Classes/Issues/Referenced/IssueReferencedModel.swift
Classes/Views/AttributedStringView.swift

Don't collide gestures on AttributedStringView

---

Classes/Repository/RepositoryCodeBlobViewController.swift
Classes/Repository/RepositoryCodeDirectoryViewController.swift

Fix repo blob loading bug

---

Classes/Repository/RepositoryCodeBlobViewController.swift
Classes/Repository/RepositoryCodeDirectoryViewController.swift
Classes/Views/CodeView.swift

Repo code highlighting

---

Classes/View Controllers/BaseListViewController.swift

I'm not sure why this was never the case.... 😱

Actually show an empty state on base list vc

---

Classes/Repository/RepositoryOverviewViewController.swift

Convert readme to base list vc

---

Classes/Views/AttributedStringCell.swift

Fixes #1020 
Fixes #1143 
We should look at the individual subclasses and check if they need some improvements, but they are looking OK, so I will leave that for another PR.

Provide generated a11x for AttributedStringCells

---

Classes/Models/FilePath.swift
Classes/Repository/RepositoryCodeBlobViewController.swift
Classes/Repository/RepositoryCodeDirectoryViewController.swift
Classes/View Controllers/UINavigationItem+TitleSubtitle.swift
Freetime.xcodeproj/project.pbxproj
FreetimeTests/FilePathTests.swift

Refactor dir and blob paths, add tests

---

Classes/Issues/Managing/IssueManagingExpansionCell.swift

Manage button respects safe area

---

Classes/Settings/Settings.storyboard

Right align API status in settings

---

Classes/View Controllers/UINavigationItem+TitleSubtitle.swift

Auto shrink title label

---

Classes/Views/TextActionsController.swift

Fixes #1155 
Did this ever work on iPad? cc @Sherlouk

Image upload works on iPad

---

Classes/Systems/ScrollViewKeyboardAdjuster.swift

Only change inset when kb was previously shown

---

Classes/Views/DotListView.swift

Added dot list reload if collection view frame changes

---

Classes/Issues/GithubClient+Issues.swift
Classes/Issues/Milestone/IssueMilestoneCell.swift
Classes/Issues/Milestone/IssueMilestoneSectionController.swift
Classes/Milestones/Milestone.swift
gql/API.swift
gql/Fragments.graphql

Milestone progress view

---

Classes/Issues/Files/File+ListDiffable.swift

Make File object actually unique

---

Classes/Systems/Rating/RatingController.swift

Log when prompting for rating

---

Local Pods/MMMarkdown/Source/MMSpanParser.m

Fixes #1192
Need to keep an eye out for side effects

Allow whitespace in table columns

---

Classes/Systems/NSAttributedStringSizing.swift

Round label background rects

---

Classes/Views/AttributedStringView.swift

Fix tap-expansion bug on comments

---

Classes/Settings/Settings.storyboard
Classes/Settings/SettingsLabel.swift
Classes/Systems/GithubHighlighting.swift
Classes/Views/Styles.swift
Freetime.xcodeproj/project.pbxproj
Local Pods/Highlightr/Pod/Classes/Highlightr.swift
Local Pods/Highlightr/Pod/Classes/Theme.swift

Dynamic content size support

---

Classes/Issues/Assignees/IssueAssigneesSectionController.swift
Classes/Issues/Files/IssueViewFilesCell.swift
Classes/Issues/Files/IssueViewFilesSectionController.swift
Classes/Issues/Labeled/IssueLabeledModel.swift
Classes/Issues/Labels/IssueLabelsSectionController.swift
Classes/Issues/Managing/IssueManagingActionCell.swift
Classes/Issues/Managing/IssueManagingSectionController.swift
Classes/Issues/Milestone/IssueMilestoneCell.swift
Classes/Issues/Milestone/IssueMilestoneSectionController.swift
Classes/Issues/Status/IssueStatusSectionController.swift
Classes/Systems/NSAttributedStringSizing.swift
Classes/Views/LabelListCell.swift
Classes/Views/Styles.swift
Classes/Views/UIButton+Label.swift

Polish header spacing

---

Classes/Issues/IssuesViewController.swift

Use collab permissions for issue editing

---

Classes/Issues/IssueTextActionsView.swift

Remove unused label from actions cell

---

Classes/Repository/RepositoryViewController.swift

Master repo VC background is white

---

Local Pods/MMMarkdown/Source/MMSpanParser.m

Scan for ellipsis in urls

---

Classes/Issues/MilestoneEvent/IssueMilestoneEventModel.swift

Milestone events have date

---

Classes/Settings/Settings.storyboard

Api status label respects content size

---

Classes/Notifications/NoNewNotificationsCell.swift
Classes/Notifications/NoNewNotificationsSectionController.swift
Classes/Notifications/NotificationEmptyMessageClient.swift
Classes/Systems/AppDelegate.swift

Init firebase db once, avoid flickering view

---

Classes/New Issue/NewIssue.storyboard

Bigger tap target on new issue title

---

Classes/Issues/Milestone/IssueMilestoneCell.swift

Invert milestone progress

---

Classes/Issues/Commit/IssueCommitCell.swift

IssueCommitCell is a button, add ax label

---

Classes/Issues/GithubClient+Issues.swift
Classes/Issues/Issue+IssueType.swift
Classes/Issues/IssueViewModels.swift
Classes/Issues/PullRequest+IssueType.swift
Classes/Milestones/Milestone.swift
Classes/Notifications/Notification+NotificationViewModel.swift
Classes/PullReqeustReviews/GithubClient+PullRequestReviewComments.swift
Classes/Repository/RepositoryClient.swift
Classes/Systems/String+GithubDate.swift
Freetime.xcodeproj/project.pbxproj

Refactor date formatting from String

---

Classes/Issues/Comments/Markdown/CommentModelsFromMarkdown.swift
Classes/Issues/Comments/Markdown/MMElement+Attributes.swift
Local Pods/MMMarkdown/Source/MMElement.h
Local Pods/MMMarkdown/Source/MMElement.m
Local Pods/MMMarkdown/Source/MMMarkdownExtensions.h
Local Pods/MMMarkdown/Source/MMSpanParser.m

Find usernames in MMMarkdown

---

Classes/Issues/Comments/Markdown/CommentModelsFromMarkdown.swift
Local Pods/MMMarkdown/Source/MMElement.h
Local Pods/MMMarkdown/Source/MMElement.m
Local Pods/MMMarkdown/Source/MMMarkdownExtensions.h
Local Pods/MMMarkdown/Source/MMParser.m

Parse checkboxes in MMMarkdown

---

Classes/Issues/Comments/Markdown/CommentModelsFromMarkdown.swift
Classes/Issues/Comments/Markdown/MMElement+Attributes.swift
FreetimeTests/MMMarkdownASTTests.swift
Local Pods/MMMarkdown/Source/MMElement.h
Local Pods/MMMarkdown/Source/MMElement.m
Local Pods/MMMarkdown/Source/MMMarkdown.m
Local Pods/MMMarkdown/Source/MMParser.h
Local Pods/MMMarkdown/Source/MMParser.m
Local Pods/MMMarkdown/Source/MMSpanParser.h
Local Pods/MMMarkdown/Source/MMSpanParser.m

Parse issue shorthand within MMMarkdown

---

Classes/Issues/Comments/IssueCommentSectionController.swift
Classes/Issues/Comments/Markdown/CommentModelsFromMarkdown.swift
Classes/Issues/Comments/Markdown/MarkdownAttribute.swift
Classes/Issues/Comments/Markdown/MarkdownCheckboxModel.swift
Classes/Issues/IssueCommentModelHandling.swift
Classes/Issues/Preview/IssuePreviewSectionController.swift
Classes/Issues/Review/IssueReviewSectionController.swift
Classes/Repository/RepositoryReadmeSectionController.swift
Classes/Views/AttributedStringView.swift
Freetime.xcodeproj/project.pbxproj

Tapping checkboxes updates the UI and edits on the server

---

Classes/Issues/Comments/Details/IssueCommentDetailCell.swift
Classes/Issues/Comments/IssueCommentSectionController.swift
Classes/Issues/Comments/Reactions/ReactionViewModel.swift
Classes/Issues/Files/IssueFilesViewController.swift
Classes/Issues/Files/IssueViewFilesCell.swift
Classes/Issues/IssuesViewController.swift
Classes/Milestones/MilestoneCell.swift
Classes/Repository/RepositorySummaryCell.swift
Classes/Systems/Signature.swift
Classes/Utility/AlertAction.swift
Classes/Utility/Bundle+Version.swift
Classes/Views/Date+Display.swift

Fix Int format crash + unify String localization

---

Classes/Systems/AppDelegate.swift
Classes/Utility/LogEnvironmentInformation.swift
Freetime.xcodeproj/project.pbxproj

I'd like to get a better understanding of user demographics to prioritize other languages, accessibility, and RTL. Doesn't mean if there are very few users we give up. Also justification for working on stuff, knowing that we're helping ppl.
However I could understand push back against logging ppl's information. If people strongly disagree, I wont merge this.

Log device environment info

---

Freetime.xcodeproj/project.pbxproj

Fix build from file moves

---

Classes/Issues/Renamed/IssueRenamedCell.swift

Rename event title inset

---

Classes/Repository/RepositoryCodeDirectoryViewController.swift

Error message for repo dir

---

Classes/Notifications/NotificationsViewController.swift

Notification alert ipad crash

---

Classes/Systems/PhotoViewHandler.swift

Prevent tapping svgs

---

Classes/Views/CodeView.swift

CodeView must use stock UITextView to be memory efficient

---

Classes/Issues/Comments/Reactions/IssueCommentReactionCell.swift
Classes/Issues/Comments/Reactions/IssueReactionCell.swift

Reaction cell size is actually calculated

---

Classes/Issues/Comments/IssueCommentSectionController.swift
Classes/Issues/Referenced/IssueReferencedSectionController.swift

Properly present VC from reference events

---

Classes/Notifications/NotificationCell.swift
Classes/Notifications/NotificationSectionController.swift
Classes/Utility/Int+Abbreviated.swift
Freetime.xcodeproj/project.pbxproj

Adjust layout of notification cells

---

Classes/Issues/Managing/IssueManagingActionCell.swift
Classes/Issues/Managing/IssueManagingSectionController.swift

Mute colors of action buttons

---

Classes/Issues/IssuesViewController.swift
Classes/Views/UIScrollView+ScrollToBottom.swift

Fix bottom scroll offset positions

---

Classes/Issues/Assignees/IssueAssigneeUserCell.swift
Classes/Issues/Files/IssueViewFilesCell.swift
Classes/Issues/Milestone/IssueMilestoneCell.swift
Classes/Views/LabelListCell.swift

Safe area insets for milestone and assignees

---

Classes/Image Upload/ImageUpload.storyboard
Classes/Image Upload/ImageUploadTableViewController.swift
Classes/New Issue/NewIssueTableViewController.swift
Classes/Settings/SettingsViewController.swift

Placeholder on image upload consistent

---

Classes/Issues/IssuesViewController.swift
Classes/Issues/Managing/IssueManagingModel.swift
Classes/Issues/Managing/IssueManagingSectionController.swift

Author can close their own issues and PRs

---

AppStore.md

Add app store metadata for contribution

---

Classes/Issues/Comments/IssueCommentBaseCell.swift
Classes/Issues/DiffHunk/IssueDiffHunkPathCell.swift
Classes/Issues/DiffHunk/IssueDiffHunkPreviewCell.swift
Classes/Issues/DiffHunk/IssueDiffHunkSectionController.swift
Classes/Issues/Review/IssueReviewDetailsCell.swift
Classes/Issues/Review/IssueReviewEmptyTailCell.swift
Classes/Issues/Review/IssueReviewSectionController.swift
Classes/Issues/Review/IssueReviewViewCommentsCell.swift
Classes/Views/Styles.swift

PR review thread with new card design

---

Classes/Milestones/GithubClient+Milestones.swift

Sort milestones by due date and title

---

Classes/Notifications/NotificationsViewController.swift

Consistency w/ rest of the app

Notifications VC back item empty

---

Classes/Issues/IssueTextActionsView.swift

Give markdown actions more spacing

---

Classes/Models/FilePath.swift
Classes/Repository/RepositoryCodeBlobViewController.swift
Classes/Repository/RepositoryCodeDirectoryViewController.swift
Classes/View Controllers/UIViewController+FilePathTitle.swift
Freetime.xcodeproj/project.pbxproj

Use new dropdown for browsing files

---

Classes/View Controllers/UIViewController+FilePathTitle.swift

From https://github.com/rnystrom/GitHawk/pull/1400#issuecomment-357469290.

Add "Jump to..." to make an action sheet more expressive

---

Classes/Repository/RepositoryViewController.swift

Removes user name action from repo view

---

Classes/Issues/Comments/IssueCommentSectionController.swift
Classes/Issues/Comments/Reactions/IssueCommentReactionCell.swift

Disable uncollapse when menu visible

---

Classes/Labels/LabelsViewController.swift
Classes/Milestones/MilestonesViewController.swift

Empty view for labels and milestones

---

Classes/Views/BoundedImageSize.swift

cap image heights

---

Classes/Issues/Comments/IssueCommentBaseCell.swift

More bubble hidden on reuse

---

Classes/Issues/Comments/IssueCommentBaseCell.swift
Classes/Section Controllers/LoadMore/LoadMoreSectionController.swift

Spinner on generic load more

---

Local Pods/MessageViewController/MessageViewController/MessageViewController.swift

Trim whitespace and newline from text cache

---

Local Pods/MessageViewController/MessageViewController/MessageViewController.swift

Fix nil scrollview in message VC

---

Classes/Issues/IssuesViewController.swift
Classes/Utility/AlertAction.swift

Fix bad link for profiles

---

Classes/Labels/LabelsViewController.swift
Classes/Milestones/MilestonesViewController.swift

Hide bg view while loading labels/milestones

---

Classes/Issues/Comments/Html/IssueCommentHtmlCell.swift

[object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) tag.
Fixes #1437

Set content mode for IssueCommentHtmlCell's image

---

Resources/Info.plist

Add ios 11 save to library permissions

---

Classes/Issues/Comments/Html/IssueCommentHtmlCell.swift

Fixes #1441, should help w/ #1339

Remove KVO and just ask the webview how tall it is

---

Classes/Issues/Comments/Html/IssueCommentHtmlCell.swift
Classes/Issues/Managing/IssueManagingModel.swift

Fixes #1446
Fixes #1387
Fixes #1298

Update HTML cell height on content height change

---

Classes/Issues/Comments/Html/IssueCommentHtmlCell.swift

Noticed a bug w/ @iglistkit-bot comments. The height never changes, so the JavaScript never detects an update. Instead, query the height on load finish _in addition_ to polling.

Query webview when height doesnt change

---

Classes/Notifications/NotificationsViewController.swift

Only update the mark all state, don't re-init the button

---

Classes/Views/NavigationTitleDropdownView.swift

Add a11x button trait to dropdown

---

Classes/Issues/DiffHunk/IssueDiffHunkModel.swift
Classes/Issues/IssuesViewController.swift
Classes/Issues/PullRequest+IssueType.swift
Classes/PullRequestReviews/GithubClient+PullRequestReviewComments.swift
Classes/PullRequestReviews/PullRequestReviewCommentsViewController.swift
Classes/PullRequestReviews/PullRequestReviewReplyCell.swift
Classes/PullRequestReviews/PullRequestReviewReplyModel.swift
Classes/PullRequestReviews/PullRequestReviewReplySectionController.swift
Classes/Systems/ListAdapter+Scrolling.swift
Classes/Views/MessageView+Styles.swift
Freetime.xcodeproj/project.pbxproj

- Add "Reply" button to tail of each thread
- Tapping button displays `MessageTextView` (same as in Issue/PR VC)
- Hitting send will reply to that thread + hide the text view
Fixes #874

Reply to Pull Request Review comments

---

Classes/Issues/Managing/IssueManagingActionCell.swift

Updated action button styles

---

Classes/Views/Styles.swift
Podfile.lock
Pods/Local Podspecs/StyledText.podspec.json
Pods/Manifest.lock
Pods/Pods.xcodeproj/project.pbxproj
Pods/StyledText/StyledText/StyledTextBuilder.swift
Pods/StyledText/StyledText/TextStyle.swift
Settings.bundle/com.mono0926.LicensePlist.plist

Update StyledText and fix semibold fonts

---

Classes/Systems/Autocomplete/AutocompleteController.swift
Classes/Systems/Autocomplete/AutocompleteType.swift
Classes/Systems/Autocomplete/EmojiAutocomplete.swift
Classes/Systems/Autocomplete/IssueCommentAutocomplete.swift
Classes/Systems/Autocomplete/UserAutocomplete.swift

Username highlighting

---

Classes/Issues/Files/IssueFilesViewController.swift
Classes/Notifications/NoNewNotificationsSectionController.swift
Classes/Notifications/NotificationsViewController.swift
Classes/Repository/Empty/RepositoryEmptyResultsSectionController.swift
Classes/Repository/RepositoryCodeDirectoryViewController.swift
Classes/Repository/RepositoryIssuesViewController.swift
Classes/Repository/RepositoryOverviewViewController.swift
Classes/Search/SearchNoResultsSectionController.swift
Classes/Search/SearchViewController.swift
Classes/Systems/ScrollViewKeyboardAdjuster.swift

Hey guys :)
Just fixing the topLayoutGuide and bottomLayoutGuide warnings :))

Fixing topLayoutGuide and bottomLayoutGuide iOS 11 deprecated Warnings

---

Classes/Issues/Files/IssuePatchContentViewController.swift

Hey guys :))
I think this fix #1513

Fixing File changes has content under nav bar

---

Classes/Issues/IssuesViewController.swift

Smarter auto scroll to last element

---

Classes/Views/IssueTextActionsView+Markdown.swift

Mention bar action should wrap at current selection

---

Classes/Issues/Merge/GithubClient+Merge.swift
Classes/Issues/Merge/IssueMergeButtonCell.swift
Classes/Issues/Merge/IssueMergeButtonModel.swift
Classes/Issues/Merge/IssueMergeSectionController.swift
Classes/Issues/Merge/MergeButton.swift

Loading state and show merge error message

---

Classes/Issues/Comments/Html/IssueCommentHtmlCell.swift

Strip root image paths from html

---

Classes/Repository/RepositoryCodeBlobViewController.swift
Classes/Systems/GithubHighlighting.swift
Classes/Views/CodeView.swift

Hey guys :)
I think this fixes #1454

Fixing files dont have code highlighting

---

Classes/Issues/Merge/IssueMergeSectionController.swift
Classes/Issues/Merge/IssueMergeSummaryCell.swift
Classes/Issues/Merge/IssueMergeSummaryModel.swift

Add support for pending merges

---

Freetime.xcodeproj/project.pbxproj
Freetime.xcodeproj/xcshareddata/xcschemes/Freetime-AppCenter.xcscheme
FreetimeTests/Bookmark Tests/BookmarkViewModelTests.swift
FreetimeTests/DateDisplayTests.swift
FreetimeTests/EmojiTests.swift
FreetimeTests/GraphQLIDDecodeTests.swift
FreetimeTests/IssueLabelCellTests.swift
FreetimeTests/IssueTests.swift
FreetimeTests/ListKitTestCase.swift
FreetimeTests/ListTestKit.swift
FreetimeTests/MMMarkdownASTTests.swift
FreetimeTests/Mocks/MockSearchEmptyViewDelegate.swift
FreetimeTests/ReactionTests.swift
FreetimeTests/Search Tests/SearchEmptyViewTests.swift
FreetimeTests/Search Tests/SearchQueryTests.swift
FreetimeTests/Search Tests/SearchRecentStoreTests.swift
FreetimeTests/Search Tests/SearchRecentViewModelTests.swift
FreetimeTests/SecretsTests.swift
FreetimeTests/SignatureTests.swift
FreetimeTests/Snapshot Tests/AttributedStringViewTests.swift
FreetimeTests/SplitViewTests.swift

Weird that it's setup this way.
Changes this:
to this:

Change product name to GitHawk

---

Freetime.xcodeproj/project.pbxproj
Freetime.xcodeproj/xcshareddata/xcschemes/Freetime-AppCenter.xcscheme
FreetimeTests/Bookmark Tests/BookmarkViewModelTests.swift
FreetimeTests/DateDisplayTests.swift
FreetimeTests/EmojiTests.swift
FreetimeTests/GraphQLIDDecodeTests.swift
FreetimeTests/IssueLabelCellTests.swift
FreetimeTests/IssueTests.swift
FreetimeTests/ListKitTestCase.swift
FreetimeTests/ListTestKit.swift
FreetimeTests/MMMarkdownASTTests.swift
FreetimeTests/Mocks/MockSearchEmptyViewDelegate.swift
FreetimeTests/ReactionTests.swift
FreetimeTests/Search Tests/SearchEmptyViewTests.swift
FreetimeTests/Search Tests/SearchQueryTests.swift
FreetimeTests/Search Tests/SearchRecentStoreTests.swift
FreetimeTests/Search Tests/SearchRecentViewModelTests.swift
FreetimeTests/SecretsTests.swift
FreetimeTests/SignatureTests.swift
FreetimeTests/Snapshot Tests/AttributedStringViewTests.swift
FreetimeTests/SplitViewTests.swift

Reverts rnystrom/GitHawk#1545
Fixes #1561

Revert "Change product name to GitHawk"

---

Classes/Views/NavigationTitleDropdownView.swift

Fix ipad custom nav view layout

---

Classes/Issues/Managing/IssueManagingActionCell.swift
Classes/Issues/Managing/IssueManagingSectionController.swift

I dig this. Simpler, more dynamic and predictable.
Fixes #1566

Simplify action cell layout

---

Classes/Image Upload/ImageUploadTableViewController.swift
Classes/Issues/Assignees/IssueAssigneeAvatarCell.swift
Classes/Issues/Assignees/IssueAssigneeUserCell.swift
Classes/Issues/Comments/Details/IssueCommentDetailCell.swift
Classes/Issues/Comments/Images/IssueCommentImageCell.swift
Classes/Issues/Commit/IssueCommitCell.swift
Classes/Issues/IssuesViewController.swift
Classes/Login/LoginSplashViewController.swift
Classes/PullRequestReviews/PullRequestReviewCommentsViewController.swift
Classes/Repository/RepositoryIssuesViewController.swift
Classes/Settings/SettingsViewController.swift
Classes/Systems/Toast.swift
Classes/Views/UICollectionViewCell+SafeAreaContentView.swift
Classes/Views/UIScrollView+LeftRightSafeInset.swift
Classes/Views/UIScrollView+ScrollToTop.swift
Classes/Views/UIView+BottomBorder.swift

Hey guys :))
Since now the target deployment is iOS 11
Could these conditionals be removed?

Removing #available conditionals

---

Classes/Issues/IssuesViewController.swift
Classes/Issues/Merge/IssueMergeContextCell.swift
Classes/Issues/Merge/IssueMergeSummaryCell.swift
Classes/Issues/Merge/IssueMergeSummaryModel.swift
Classes/Issues/Merge/MergeButton.swift
Classes/Views/NavigationTitleDropdownView.swift

Fixes #1548 
<details>
</details>

Accessibility improvements

---

Podfile.lock
Pods/Local Podspecs/MessageViewController.podspec.json
Pods/Manifest.lock
Pods/MessageViewController/MessageViewController/MessageAutocompleteController.swift
Pods/Target Support Files/MessageViewController/Info.plist

Update message VC pod

---

Local Pods/GitHubAPI/GitHubAPI/V3Repository.swift

Fixes #1615 
(Also please write a blog post on the networking stack, it looks really interesting going through it!)

Make the repositories' desciption optional

---

docs/_posts/2018-08-03-Immutable-Model-Mutability.md

https://github.com/rnystrom/GitHawk/blob/mutate-blog/docs/_posts/2018-08-03-Immutable-Model-Mutability.md

Immutability with mutability blog post

---

Classes/Issues/Files/IssueFileCell.swift
Classes/Issues/Files/IssueFilesViewController.swift
Classes/Issues/Files/IssuePatchContentViewController.swift
Classes/Models/File.swift
Local Pods/GitHubAPI/GitHubAPI/V3File.swift

Show files without patches

---

Classes/Issues/Merge/MergeButton.swift

Create a custom UIAccessibilityElement for the merge button

---

Classes/Issues/Managing/IssueManagingSectionController.swift
Classes/Labels/Labels.storyboard
Classes/Labels/LabelsViewController.swift
Classes/Milestones/Milestones.storyboard
Classes/Milestones/MilestonesViewController.swift
Classes/People/PeopleCell.swift
Classes/People/PeopleViewController.swift

Test out context menu on labels, people, milestones

---

Classes/Views/Constants.swift
FreetimeTests/ReactionTests.swift
Local Pods/GitHubAPI/GitHubAPI.podspec
Local Pods/GitHubSession/GitHubSession.podspec

Remove references to old url

---

Classes/Settings/SettingsAccountsViewController.swift
Classes/Systems/AppDelegate.swift
Classes/Systems/ShortcutHandler.swift

Update 3D touch items when switching account.

---

Classes/Issues/Managing/IssueManagingSectionController.swift
Classes/Labels/Labels.storyboard
Classes/Labels/LabelsViewController.swift
Classes/Milestones/Milestones.storyboard
Classes/Milestones/MilestonesViewController.swift
Classes/Models/RepositoryLabel.swift
Classes/People/PeopleViewController.swift
Pods/ContextMenu/ContextMenu/ContextMenuDelegate.swift
Pods/ContextMenu/ContextMenu/UIViewController+Extensions.swift

Remove done button from context menu VCs

---

Classes/Notifications/NotificationsViewController.swift

This resolves #1641 by rename "Archived" to "All" :)

Rename "Archived" to "All"

---

Classes/Systems/Toast.swift

Fixes https://github.com/GitHawkApp/Toast/issues/1

Make Toast init non-optional, post a11y notification

---

Classes/Notifications/NotificationClient.swift
Classes/Notifications/NotificationsViewController.swift
Local Pods/GitHubAPI/GitHubAPI/V3NotificationRequest.swift
Local Pods/GitHubAPI/GitHubAPI/V3RepositoryNotificationRequest.swift

Readd repo notifications

---

Classes/Issues/Comments/Markdown/CMarkParsing.swift
Podfile.lock
Pods/Manifest.lock
Pods/cmark-gfm-swift/Source/Block+ListElement.swift
Pods/cmark-gfm-swift/Source/Block+TableRow.swift
Pods/cmark-gfm-swift/Source/Block+TextElement.swift
Pods/cmark-gfm-swift/Source/Inline+TextElement.swift
Pods/cmark-gfm-swift/Source/Node+Elements.swift
Pods/cmark-gfm-swift/Source/SwiftAST.swift
Pods/cmark-gfm-swift/Source/cmark_gfm/include/checkbox.h
Pods/cmark-gfm-swift/Source/cmark_gfm/include/mention.h

Update cmark lib with HTML fixes

---

Classes/Systems/AppDelegate.swift
Classes/Systems/BadgeNotifications.swift

Retain badge object when fetching notifications

---

Classes/Issues/Comments/IssueCommentSectionController.swift

Reply button on comments

---

Classes/Issues/IssuesViewController.swift

Support the case for IssueTargetBranchModel

---

Classes/Settings/SettingsViewController.swift

I missed this in #1652.
Finally fixes the bug reporter in-app. 🙏

Link to the right repo

---

Freetime.xcodeproj/project.pbxproj
Podfile.lock
Pods/Manifest.lock
Pods/cmark-gfm-swift/Source/Inline+TextElement.swift
Pods/cmark-gfm-swift/Source/cmark_gfm/blocks.c
Pods/cmark-gfm-swift/Source/cmark_gfm/checkbox.c
Pods/cmark-gfm-swift/Source/cmark_gfm/include/cmark.h
Pods/cmark-gfm-swift/Source/cmark_gfm/include/node.h
Pods/cmark-gfm-swift/Source/cmark_gfm/include/parser.h

Update cmark with checkbox support

---

Classes/View Controllers/AppSplitViewController.swift
Freetime.xcodeproj/project.pbxproj
Resources/Base.lproj/Main.storyboard

Fix flickering when navigating back

---

Classes/Notifications/NotificationsViewController.swift

Always update inbox when receiving changes

---

Classes/Issues/Comments/Markdown/CMarkParsing.swift

Show empty string when no markdown

---

Classes/Repository/GQL+RepositoryIssueSummaryType.swift
Classes/Repository/RepositoryClient.swift
Classes/Repository/RepositoryIssuesViewController.swift
Classes/Section Controllers/SearchBar/SearchBarSectionController.swift
gql/API.swift
gql/RepoPages.graphql

GitHub syntax search

---

Classes/Issues/Merge/IssueMergeSectionController.swift

Add title to merge toggle

---

Classes/Issues/Comments/Markdown/String+DetectShortlink.swift

Use utf16 for tag ranges

---

Classes/Issues/Managing/IssueManagingActionModel.swift
Classes/Issues/Managing/IssueManagingSectionController.swift

Requires updating IGLK Swift branch

Update action label when value changes, make actions diffable

---

Classes/Issues/Labeled/IssueLabeledModel.swift

Add extra space for label events

---

Classes/Issues/Comments/CodeBlock/IssueCommentCodeBlockCell.swift
Classes/Issues/Comments/CodeBlock/IssueCommentCodeBlockModel.swift
Classes/Issues/Comments/Markdown/CMarkParsing.swift
Classes/Issues/Comments/Markdown/CodeBlockModel.swift
Classes/Systems/GithubHighlighting.swift

Code blocks share system font adjustment, use StyledText

---

Classes/Repository/RepositoryIssuesViewController.swift

Add space to default search string

---

Podfile.lock
Pods/Manifest.lock
Pods/cmark-gfm-swift/Source/cmark_gfm/checkbox.c
Pods/cmark-gfm-swift/Source/cmark_gfm/mention.c

Update cmark lib to fix html render crashes

---

Podfile.lock
Pods/Manifest.lock
Pods/StyledText/StyledText/StyledText.swift

Update styled text lib

---

Classes/Issues/Comments/Markdown/CodeBlockModel.swift

I couldn't trip the Main Thread Checker diagnostics tool or reproduce the warning after making this adjustment, so I'm hoping this resolves #1225.

resolves warning about updating UI on background thread 

---

Classes/Issues/Comments/IssueCommentSectionController.swift
Classes/Issues/Comments/Markdown/ViewMarkdownViewController.swift
Freetime.xcodeproj/project.pbxproj

Easy way to copy/paste select stuff.

View raw markdown on comments

---

Classes/Issues/IssuesViewController.swift

show issueMergeSectionController only if issue is open

---

Classes/Issues/Managing/IssueManagingSectionController.swift

Use minimal context menus for label/assign/milestones

---

Classes/Issues/GithubClient+Issues.swift
Local Pods/GitHubAPI/GitHubAPI/Client.swift

Show error from API when reaction fails

---

Classes/Repository/RepositoryCodeBlobViewController.swift

This fixes [#1891](https://github.com/GitHawkApp/GitHawk/issues/1891)

Respect safe area insets on reviewing file contents

---

FreetimeTests/IssueCommentTableTests.swift

I'm trying to sneak up on  #1790 (supporting images in markdown tables).. wrote these tests as a starting point.

Unit Test IssueCommentTable dimensions

---

Classes/Systems/Autocomplete/EmojiAutocomplete.swift

Limit emoji autocomplete search results

---

Classes/Issues/IssuesViewController.swift
Classes/Systems/Autocomplete/AutocompleteCell.swift
Classes/Systems/Autocomplete/IssueAutocomplete.swift
Classes/Systems/Autocomplete/UserAutocomplete.swift
Freetime.xcodeproj/project.pbxproj
gql/API.swift
gql/IssueAutocomplete.graphql

Autocomplete issues in Markdown

---

Classes/Issues/Merge/IssueMergeContextModel.swift
Classes/Issues/Merge/IssueMergeSectionController.swift
Classes/Issues/PullRequest+IssueType.swift
gql/API.swift
gql/Fragments.graphql

Open CI links

---

Classes/Notifications/NotificationModelController.swift

Fixes [#1895](https://github.com/GitHawkApp/GitHawk/issues/1895)

Add haptic feedback on watch/unwatch notifications

---

Classes/Notifications/NotificationCell.swift

reorders read/watch buttons

---

Classes/Issues/IssueManageButton.swift
Classes/Issues/IssueManagingContextController.swift
Classes/Issues/IssuesViewController.swift
Classes/Issues/Managing/IssueManagingSectionController.swift
Classes/Labels/LabelMenuCell.swift
Classes/Labels/LabelSectionController.swift
Classes/Labels/LabelsViewController.swift
Classes/Milestones/MilestoneCell.swift
Classes/Milestones/MilestoneSectionController.swift
Classes/Milestones/MilestonesViewController.swift
Classes/People/PeopleCell.swift
Classes/People/PeopleSectionController.swift
Classes/People/PeopleViewController.swift
Classes/View Controllers/ContrastContextMenu.swift
Classes/View Controllers/UINavigationItem+TitleSubtitle.swift
Classes/Views/Constants.swift
Classes/Views/Styles.swift
Classes/Views/UIImageView+Avatar.swift
Freetime.xcodeproj/project.pbxproj

See [tweet](https://twitter.com/_ryannystrom/status/1018636898925981698) for screenshots and videos. I'm in love with this. Feels much faster.

New ContextMenu UX for managing Issues & PRs

---

Classes/Issues/Merge/IssueMergeSectionController.swift
Classes/Views/Styles.swift

Add insets to issue with new button design

---

Classes/Labels/LabelsViewController.swift
Classes/Milestones/MilestonesViewController.swift
Classes/People/PeopleViewController.swift
Classes/View Controllers/UIViewController+MenuDone.swift
Freetime.xcodeproj/project.pbxproj

Add done button to menu VCs

---

Classes/Issues/IssueManagingContextController.swift

Add haptics on menu

---

Classes/Notifications/NotificationCell.swift

Fix selection bug on Inbox

---

Classes/View Controllers/ContrastContextMenu.swift

Added button as accessibilityTrait for the cells in the Context Menu. VoiceOver now reads out for example Labels - Button or Assignees - Button. Fixes #1948

Initial ContextMenu cells made accessibility buttons

---

Classes/Issues/IssuesViewController.swift

Add space when replying to issue comment

---

Classes/Notifications/NotificationsViewController.swift

Fix(Scroll to top of list on tap of tabbar item)

---

Classes/Notifications/NotificationSectionController.swift

Fixes [#1893](https://github.com/GitHawkApp/GitHawk/issues/1893)

Don’t send haptic if it’s already marked as read

---

Classes/Issues/Comments/Html/IssueCommentHtmlCell.swift
Resources/Assets.xcassets/splash_branches.imageset/Contents.json

Fix webview background color on iOS 12

---

Classes/Labels/LabelSectionController.swift
Classes/People/PeopleSectionController.swift
Resources/Assets.xcassets/splash_branches.imageset/Contents.json

Fix label and people selection states

---

Classes/Notifications/NotificationCell.swift
Classes/Notifications/NotificationSectionController.swift

Add animation when marking read

---

Classes/Issues/IssueManagingContextController.swift

Dont show menu button if no actions

---

Classes/Settings/SettingsViewController.swift

Use latest account when switching

---

Classes/Views/SelectableCell.swift

Fix selection overlay disabling buttons

---

Classes/Issues/Comments/Reactions/IssueCommentReactionCell.swift

More hit area with more button

---

Podfile.lock
Pods/Manifest.lock
Pods/Squawk/Source/SquawkItem.swift
Settings.bundle/com.mono0926.LicensePlist.plist

Update Squawk to fix crash

---

Classes/Systems/RootNavigationManager.swift

Login should render inbox

---

Classes/Issues/EditComment/EditCommentViewController.swift
Classes/Issues/IssueTextActionsView.swift
Classes/Issues/IssuesViewController.swift
Classes/New Issue/NewIssueTableViewController.swift
Classes/PullRequestReviews/PullRequestReviewCommentsViewController.swift
Classes/Views/IssueTextActionsView+Markdown.swift
Classes/Views/MessageView+Styles.swift

New send button position

---

Classes/Repository/GQL+RepositoryIssueSummaryType.swift
Classes/Repository/RepositorySummaryCell.swift
Classes/Repository/RepositorySummarySectionController.swift

Repo PRs render PR icon, more whitespace

---

Classes/Settings/Settings.storyboard
Classes/Settings/SettingsViewController.swift
Classes/Views/StyledSwitch.swift
Freetime.xcodeproj/project.pbxproj

Switches share style, fix default reaction padding

---

Classes/Issues/IssueManagingContextController.swift

Don't display any actions when you don't have permissions

---

Classes/Systems/RootNavigationManager.swift

Fixes #2096
**Note:**
I'm not sure that my solution is good because that's not a good idea to use `dismiss` property from `didFocus` method but I didn't find any better. If anyone knows some solution better - you are welcome

Changing accounts resets to main tab fix

---

Classes/Issues/Comments/Reactions/IssueCommentReactionCell.swift

Fix action delay with reactions menu

---

.github/ISSUE_TEMPLATE/feature_request.md

Add issue template for feature request

---

.github/ISSUE_TEMPLATE/bug_report.md

Add issue template for bug report

---

Classes/Issues/IssuesViewController.swift

Don't override entire message when replying

---

Classes/Issues/IssuesViewController.swift

Fixes bug where send button is enabled after sending a comment

Disable send after send

---

Classes/Issues/IssuesViewController.swift
Classes/Issues/Merge/IssueMergeSectionController.swift
Classes/Notifications/NotificationsViewController.swift

Shows merge status without button when you cannot merge.

Merge button status

---

Classes/Settings/Settings.storyboard

Set to custom to match the rest of settings 😀

Settings cell textColor

---

Classes/People/PeopleViewController.swift
FreetimeTests/SortUsers.swift

#2244
- moves sorting logic from fetch(page:) into type method
- unit test

PeopleVC: Sort users with self first

---

Classes/View Controllers/BaseListViewController2.swift

Was messing around and noticed this wasn't wired up! Now the "try again" button shows up for inbox 😄

Add empty error view to latest base VC

---

Classes/Repository/RepositoryClient.swift

Sorts issues after fetch

---

Classes/Settings/SettingsViewController.swift

Warn that logging out removes bookmarks

---

Classes/Issues/IssueManagingContextController.swift

Reopen menu item is green

---

Classes/Issues/Preview/IssuePreviewViewController.swift

Inset preview collection view

---

Classes/Issues/Comments/CodeBlock/IssueCommentCodeBlockCell.swift
Classes/Issues/Comments/CodeBlock/IssueCommentCodeBlockModel.swift
Classes/Issues/Comments/Hr/IssueCommentHrModel.swift
Classes/Issues/Comments/Html/IssueCommentHtmlCell.swift
Classes/Issues/Comments/Html/IssueCommentHtmlModel.swift
Classes/Issues/Comments/Images/IssueCommentImageCell.swift
Classes/Issues/Comments/Images/IssueCommentImageModel.swift
Classes/Issues/Comments/Quotes/IssueCommentQuoteCell.swift
Classes/Issues/Comments/Quotes/IssueCommentQuoteModel.swift
Classes/Issues/Comments/Summary/IssueCommentSummaryCell.swift
Classes/Issues/Comments/Summary/IssueCommentSummaryModel.swift
Classes/Issues/Comments/Tables/IssueCommentTableCell.swift
Classes/Issues/Comments/Tables/IssueCommentTableModel.swift
Classes/Issues/Comments/Text/IssueCommentTextCell.swift
Classes/Repository/Empty/RepositoryEmptyResultsSectionController.swift
Classes/Repository/Empty/RepositoryEmptyResultsSectionController2.swift
Classes/Repository/RepositoryIssuesViewController.swift
Classes/Repository/RepositoryOverviewViewController.swift
Classes/Repository/RepositoryReadmeModel.swift
Classes/Repository/RepositoryReadmeSectionController.swift
Classes/Views/StyledTextRenderer+ListDiffable.swift
Freetime.xcodeproj/project.pbxproj

Fixes #2390
Also pre-work for `IssueViewController` using the IGLK+Swift bridge

Refactor repo overview to use new base VC

---

Classes/Issues/Files/File+ListDiffable.swift
Classes/Issues/Files/IssueFilesSectionController.swift
Classes/Issues/Files/IssueFilesViewController.swift
Classes/Repository/RepositoryCodeDirectorySectionController.swift
Classes/Repository/RepositoryCodeDirectoryViewController.swift
Classes/Repository/RepositoryFile.swift
Classes/Section Controllers/Empty/EmptyMessageSectionController.swift
Freetime.xcodeproj/project.pbxproj

Refactor issue files and repo dir to new base VC

---

Classes/Bookmark/BookmarkCell.swift
Classes/Notifications/NotificationCell.swift
Classes/Notifications/NotificationType+Icon.swift

Show merge icon on inbox

---

Classes/Systems/AppDelegate.swift
Classes/Systems/AppRouter/Router.swift

Lazy, got all the pieces in place but never threaded the needle for actual deep links! Tested & working w/ a sample app.
Fixes #418

Support deep links

---

Classes/Issues/IssueManagingContextController.swift
Classes/Issues/IssuesViewController.swift
Classes/People/PeopleViewController.swift

Scroll to bottom when labels/people/milestones change

---

Classes/Models/FilePath.swift
Classes/Repository/RepositoryCodeDirectoryViewController.swift
Classes/Repository/RepositoryImageViewController.swift
Classes/Repository/RepositoryOverviewViewController.swift
Freetime.xcodeproj/project.pbxproj

Was there an issue for this? Can't find it

View images in code browser

---

Classes/Image Upload/ImageUploadTableViewController.swift
Classes/Issues/Comments/IssueCommentSectionController.swift
Classes/Settings/SettingsViewController.swift
Classes/Systems/AppRouter/IssueRoute+RoutePerformable.swift
Classes/Systems/AppRouter/RepoRoute+RoutePerformable.swift
Classes/Systems/AppRouter/RoutePerformable.swift
Classes/Systems/AppRouter/Router.swift
Classes/Systems/PhotoViewHandler.swift
Classes/View Controllers/UIViewController+Safari.swift
Classes/Views/IssueTextActionsView+Markdown.swift
Classes/Views/TextActionsController.swift

Route includes presentation style

---

Classes/Issues/Comments/Markdown/CMarkParsing.swift
FreetimeTests/IssueTests.swift

Improve Markdown breaking

---

Classes/Issues/Merge/MergeHelper.swift

Test pending wording

---

Classes/Systems/SpecialGitHubEmoji.swift
Classes/View Controllers/UIViewController+Safari.swift
Classes/Views/IssueTextActionsView+Markdown.swift

Fix profile presentation crash

---

Classes/Issues/Comments/IssueCommentSectionController.swift

Attach router when pushing from markdown attribute

---

Classes/Utility/AlertAction.swift

Wire up preview action from new-issue

---

Classes/PullRequestReviews/PullRequestReviewCommentsViewController.swift

Fix pull request commenting

---

Classes/Settings/Settings.storyboard

Updated "View Source Code" wording

---

BookmarkRepoCell.swift
Freetime.xcworkspace/contents.xcworkspacedata

Leftover from bookmark refactor

Remove out of place file

---

Classes/Settings/DefaultReactionDetailController.swift
Classes/Settings/SettingsViewController.swift
Classes/Views/Styles.swift

In this PR, I change the UISwitches colour in Settigns to blue. I think it makes more sense than green since the labelings of GitHawk are blue-ish. Additionally, I refactored some code in that group 😄

Change UISwitches colour to blue in Settings 💅🏻

---

Classes/Search/SearchViewController.swift

Add forks to search

---

Classes/Issues/IssueManagingContextController.swift
Classes/Labels/LabelMenuCell.swift
Classes/Milestones/MilestoneCell.swift
Classes/Notifications/Filter/InboxFilterController.swift
Classes/People/PeopleCell.swift
Classes/Repository/RepositoryBranches/RepositoryBranchesCell.swift
Classes/View Controllers/ContrastContextMenu.swift
Classes/Views/Styles.swift

Better AX blue for menus

---

Classes/History/PathHistoryViewController.swift
Classes/Issues/IssueManagingContextController.swift
Classes/Issues/IssuesViewController.swift
Classes/Issues/Merge/IssueMergeSectionController.swift
Classes/Issues/Merge/MergeButton.swift
Classes/Login/LoginSplashViewController.swift
Classes/Notifications/NotificationsViewController.swift
Classes/Repository/RepositoryViewController.swift
Classes/View Controllers/UIViewController+FilePathTitle.swift
Classes/Views/UIControlEffects.swift
Freetime.xcodeproj/project.pbxproj

Inspired by https://rolandleth.com/tech/blog/delightful-animations

Better button UX and animations

---

Classes/Systems/InboxZeroLoader.swift
Freetime.xcodeproj/project.pbxproj
FreetimeTests/InboxZeroLoaderTests.swift

Closes #2560
Found some issues w/ language & region (https://github.com/GitHawkApp/Holidays/issues/3)

Support inbox zero fixed holidays

---

Classes/Repository/RepositoryCodeBlobViewController.swift
Classes/Utility/GithubURL.swift
Freetime.xcodeproj/project.pbxproj
FreetimeTests/GithubURLTests.swift

I'm using handoff quite extensively (it's a great feature for me). Thus I did code blob view handoff just because sometimes it's easier to read code in a bigger screen.
There were no feature requests and from #331 I see that it's not expected that people will use handoff much. So if it looks like not a useful feature feel free to close it.

Add handoff support for code blob views

---

Classes/Issues/Labeled/IssueLabeledModel.swift
Classes/Models/RepositoryLabel.swift

This should be the proper version. Reverted `name` back into a `let` and uninitialized

Label emoji fix

---

Classes/Bookmark/BookmarkCell.swift
Classes/Bookmark/BookmarkIssueSectionController.swift
Classes/Bookmark/BookmarkRepoCell.swift
Classes/Bookmark/BookmarkRepoSectionController.swift
Classes/Bookmark/BookmarkViewController.swift

Hi all! This is my first time contributing to this project. Huge fan of the app!
This PR enables a user to remove bookmarks individually instead of clearing them all out. It uses the same pattern to remove rows as `SearchRecentSectionController`.
Feature Request: #2646

Enable individual bookmark deletes

---

Classes/Notifications/Filter/InboxFilterController.swift

I added a feature for saving the last selected inbox filter.
Fixes #2669

Save inbox preference
